version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

formats:
  - pdf
  - htmlzip

sphinx:
  configuration: docs/conf.py

python:
  version: 3.9
  install:
    - requirements: requirements_doc.txt
