apitypes = {
    'DWORD':        'unsigned int',
    'HANDLE':       'unsigned int',
}

api = {
    # libc
    '*.main_entry':( 'int', None, 'stdcall', '*.main_entry', (('int', None), ('int', None), ('int', None)) ),
    '*._cicos':( 'int', None, 'cdecl', '*._CIcos', () ),
    '*._cilog':( 'int', None, 'cdecl', '*._CIlog', () ),
    '*._cipow':( 'int', None, 'cdecl', '*._CIpow', () ),
    '*._cisin':( 'int', None, 'cdecl', '*._CIsin', () ),
    '*._cisqrt':( 'int', None, 'cdecl', '*._CIsqrt', () ),
    '*.__isascii':( 'int', None, 'cdecl', '*.__isascii', (('int', None),) ),
    '*.__iscsym':( 'int', None, 'cdecl', '*.__iscsym', (('int', None),) ),
    '*.__iscsymf':( 'int', None, 'cdecl', '*.__iscsymf', (('int', None),) ),
    '*.__toascii':( 'int', None, 'cdecl', '*.__toascii', (('int', None),) ),
    '*._alldiv':( 'int', None, 'stdcall', '*._alldiv', (('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._alldvrm':( 'int', None, 'stdcall', '*._alldvrm', (('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._allmul':( 'int', None, 'stdcall', '*._allmul', (('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._alloca_probe':( 'int', None, 'cdecl', '*._alloca_probe', () ),
    '*._allrem':( 'int', None, 'stdcall', '*._allrem', (('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._allshl':( 'int', None, 'cdecl', '*._allshl', () ),
    '*._allshr':( 'int', None, 'cdecl', '*._allshr', () ),
    '*._atoi64':( 'int', None, 'cdecl', '*._atoi64', (('int', None),) ),
    '*._aulldiv':( 'int', None, 'stdcall', '*._aulldiv', (('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._aulldvrm':( 'int', None, 'stdcall', '*._aulldvrm', (('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._aullrem':( 'int', None, 'stdcall', '*._aullrem', (('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._aullshr':( 'int', None, 'cdecl', '*._aullshr', () ),
    '*._chkstk':( 'int', None, 'cdecl', '*._chkstk', () ),
    '*._fltused':( 'int', None, 'cdecl', '*._fltused', () ),
    '*._ftol':( 'int', None, 'cdecl', '*._ftol', () ),
    '*._i64toa':( 'int', None, 'msfastcall', '*._i64toa', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._i64tow':( 'int', None, 'msfastcall', '*._i64tow', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._itoa':( 'int', None, 'cdecl', '*._itoa', (('int', None), ('void *', 'obj'), ('int', None)) ),
    '*._itow':( 'int', None, 'cdecl', '*._itow', (('int', None), ('void *', 'obj'), ('int', None)) ),
    '*._lfind':( 'int', None, 'cdecl', '*._lfind', (('int', None), ('int', None), ('int', None), ('int', None), ('void *', 'funcptr')) ),
    '*._ltoa':( 'int', None, 'cdecl', '*._ltoa', (('int', None), ('void *', 'obj'), ('int', None)) ),
    '*._ltow':( 'int', None, 'cdecl', '*._ltow', (('int', None), ('void *', 'obj'), ('int', None)) ),
    '*._memccpy':( 'int', None, 'cdecl', '*._memccpy', (('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._memicmp':( 'int', None, 'cdecl', '*._memicmp', (('int', None), ('int', None), ('int', None)) ),
    '*._snprintf':( 'int', None, 'cdecl', '*._snprintf', (('int', None), ('int', None), ('int', None)) ),
    '*._snwprintf':( 'int', None, 'cdecl', '*._snwprintf', (('void *', 'ptr'), ('int', None), ('void *', 'ptr')) ),
    '*._splitpath':( 'int', None, 'cdecl', '*._splitpath', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._strcmpi':( 'int', None, 'cdecl', '*._strcmpi', (('int', None), ('int', None)) ),
    '*._stricmp':( 'int', None, 'cdecl', '*._stricmp', (('int', None), ('int', None)) ),
    '*._strlwr':( 'int', None, 'cdecl', '*._strlwr', (('int', None),) ),
    '*._strnicmp':( 'int', None, 'cdecl', '*._strnicmp', (('int', None), ('int', None), ('int', None)) ),
    '*._strupr':( 'int', None, 'cdecl', '*._strupr', (('int', None),) ),
    '*._tolower':( 'int', None, 'cdecl', '*._tolower', (('int', None),) ),
    '*._toupper':( 'int', None, 'cdecl', '*._toupper', (('int', None),) ),
    '*._ui64toa':( 'int', None, 'msfastcall', '*._ui64toa', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._ui64tow':( 'int', None, 'msfastcall', '*._ui64tow', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._ultoa':( 'int', None, 'cdecl', '*._ultoa', (('int', None), ('void *', 'obj'), ('int', None)) ),
    '*._ultow':( 'int', None, 'cdecl', '*._ultow', (('int', None), ('void *', 'obj'), ('int', None)) ),
    '*._vsnprintf':( 'int', None, 'cdecl', '*._vsnprintf', (('void *', 'ptr'), ('int', None), ('int', None), ('int', None)) ),
    '*._vsnwprintf':( 'int', None, 'cdecl', '*._vsnwprintf', (('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._wcsicmp':( 'int', None, 'cdecl', '*._wcsicmp', (('int', None), ('int', None)) ),
    '*._wcslwr':( 'int', None, 'cdecl', '*._wcslwr', (('int', None),) ),
    '*._wcsnicmp':( 'int', None, 'cdecl', '*._wcsnicmp', (('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*._wcsupr':( 'int', None, 'cdecl', '*._wcsupr', (('int', None),) ),
    '*._wtoi':( 'int', None, 'cdecl', '*._wtoi', (('int', None),) ),
    '*._wtoi64':( 'int', None, 'cdecl', '*._wtoi64', (('int', None),) ),
    '*._wtol':( 'int', None, 'cdecl', '*._wtol', (('int', None),) ),
    '*.abs':( 'int', None, 'cdecl', '*.abs', (('int', None),) ),
    '*.atan':( 'int', None, 'cdecl', '*.atan', () ),
    '*.atoi':( 'int', None, 'cdecl', '*.atoi', (('int', None),) ),
    '*.atol':( 'int', None, 'cdecl', '*.atol', (('int', None),) ),
    '*.bsearch':( 'int', None, 'cdecl', '*.bsearch', (('void *', 'ptr'), ('int', None), ('int', None), ('int', None), ('void *', 'funcptr')) ),
    '*.ceil':( 'int', None, 'cdecl', '*.ceil', () ),
    '*.cos':( 'int', None, 'cdecl', '*.cos', () ),
    '*.fabs':( 'int', None, 'cdecl', '*.fabs', (('int', None), ('int', None)) ),
    '*.floor':( 'int', None, 'cdecl', '*.floor', () ),
    '*.isalnum':( 'int', None, 'cdecl', '*.isalnum', (('int', None),) ),
    '*.isalpha':( 'int', None, 'cdecl', '*.isalpha', (('int', None),) ),
    '*.iscntrl':( 'int', None, 'cdecl', '*.iscntrl', (('int', None),) ),
    '*.isdigit':( 'int', None, 'cdecl', '*.isdigit', (('int', None),) ),
    '*.isgraph':( 'int', None, 'cdecl', '*.isgraph', (('int', None),) ),
    '*.islower':( 'int', None, 'cdecl', '*.islower', (('int', None),) ),
    '*.isprint':( 'int', None, 'cdecl', '*.isprint', (('int', None),) ),
    '*.ispunct':( 'int', None, 'cdecl', '*.ispunct', (('int', None),) ),
    '*.isspace':( 'int', None, 'cdecl', '*.isspace', (('int', None),) ),
    '*.isupper':( 'int', None, 'cdecl', '*.isupper', (('int', None),) ),
    '*.iswalpha':( 'int', None, 'cdecl', '*.iswalpha', (('int', None),) ),
    '*.iswctype':( 'int', None, 'cdecl', '*.iswctype', (('int', None), ('int', None)) ),
    '*.iswdigit':( 'int', None, 'cdecl', '*.iswdigit', (('int', None),) ),
    '*.iswlower':( 'int', None, 'cdecl', '*.iswlower', (('int', None),) ),
    '*.iswspace':( 'int', None, 'cdecl', '*.iswspace', (('int', None),) ),
    '*.iswxdigit':( 'int', None, 'cdecl', '*.iswxdigit', (('int', None),) ),
    '*.isxdigit':( 'int', None, 'cdecl', '*.isxdigit', (('int', None),) ),
    '*.labs':( 'int', None, 'cdecl', '*.labs', (('int', None),) ),
    '*.log':( 'int', None, 'cdecl', '*.log', () ),
    '*.mbstowcs':( 'int', None, 'cdecl', '*.mbstowcs', (('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*.memchr':( 'int', None, 'cdecl', '*.memchr', (('int', None), ('int', None), ('int', None)) ),
    '*.memcmp':( 'int', None, 'cdecl', '*.memcmp', (('int', None), ('int', None), ('int', None)) ),
    '*.memcpy':( 'int', None, 'cdecl', '*.memcpy', (('int', None), ('int', None), ('int', None)) ),
    '*.memmove':( 'int', None, 'cdecl', '*.memmove', (('void *', 'ptr'), ('void *', 'ptr'), ('int', None)) ),
    '*.memset':( 'int', None, 'cdecl', '*.memset', (('int', None), ('int', None), ('int', None)) ),
    '*.pow':( 'int', None, 'cdecl', '*.pow', () ),
    '*.qsort':( 'int', None, 'stdcall', '*.qsort', ( ('void *', 'funcptr'), ('int', None), ('int', None), ('void *', 'funcptr'), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*.sin':( 'int', None, 'cdecl', '*.sin', () ),
    '*.sprintf':( 'int', None, 'cdecl', '*.sprintf', (('void *', 'ptr'), ('int', None)) ),
    '*.sqrt':( 'int', None, 'cdecl', '*.sqrt', () ),
    '*.sscanf':( 'int', None, 'cdecl', '*.sscanf', (('int', None), ('int', None)) ),
    '*.strcat':( 'int', None, 'cdecl', '*.strcat', (('int', None), ('int', None)) ),
    '*.strchr':( 'int', None, 'cdecl', '*.strchr', (('int', None), ('int', None)) ),
    '*.strcmp':( 'int', None, 'cdecl', '*.strcmp', (('int', None), ('int', None)) ),
    '*.strcpy':( 'int', None, 'cdecl', '*.strcpy', (('int', None), ('int', None)) ),
    '*.strcspn':( 'int', None, 'cdecl', '*.strcspn', (('int', None), ('int', None)) ),
    '*.strlen':( 'int', None, 'cdecl', '*.strlen', (('int', None),) ),
    '*.strncat':( 'int', None, 'cdecl', '*.strncat', (('int', None), ('int', None), ('int', None)) ),
    '*.strncmp':( 'int', None, 'cdecl', '*.strncmp', (('int', None), ('int', None), ('int', None)) ),
    '*.strncpy':( 'int', None, 'cdecl', '*.strncpy', (('int', None), ('int', None), ('int', None)) ),
    '*.strpbrk':( 'int', None, 'cdecl', '*.strpbrk', (('int', None), ('int', None)) ),
    '*.strrchr':( 'int', None, 'cdecl', '*.strrchr', (('int', None), ('int', None)) ),
    '*.strspn':( 'int', None, 'cdecl', '*.strspn', (('int', None), ('int', None)) ),
    '*.strstr':( 'int', None, 'cdecl', '*.strstr', (('int', None), ('int', None)) ),
    '*.strtol':( 'int', None, 'cdecl', '*.strtol', (('int', None), ('int', None), ('int', None)) ),
    '*.strtoul':( 'int', None, 'cdecl', '*.strtoul', (('int', None), ('int', None), ('int', None)) ),
    '*.swprintf':( 'int', None, 'cdecl', '*.swprintf', (('wchar *', 'ptr'), ('int', None)) ),
    '*.tan':( 'int', None, 'cdecl', '*.tan', () ),
    '*.tolower':( 'int', None, 'cdecl', '*.tolower', (('int', None),) ),
    '*.toupper':( 'int', None, 'cdecl', '*.toupper', (('int', None),) ),
    '*.towlower':( 'int', None, 'cdecl', '*.towlower', (('int', None),) ),
    '*.towupper':( 'int', None, 'cdecl', '*.towupper', (('int', None),) ),
    '*.vdbgprintex':( 'int', None, 'stdcall', '*.vDbgPrintEx', (('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*.vdbgprintexwithprefix':( 'int', None, 'stdcall', '*.vDbgPrintExWithPrefix', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*.vsprintf':( 'int', None, 'cdecl', '*.vsprintf', (('int', None), ('int', None), ('int', None)) ),
    '*.wcscat':( 'int', None, 'cdecl', '*.wcscat', (('int', None), ('void *', 'ptr')) ),
    '*.wcschr':( 'int', None, 'cdecl', '*.wcschr', (('void *', 'ptr'), ('int', None)) ),
    '*.wcscmp':( 'int', None, 'cdecl', '*.wcscmp', (('void *', 'ptr'), ('int', None)) ),
    '*.wcscpy':( 'int', None, 'cdecl', '*.wcscpy', (('void *', 'ptr'), ('void *', 'ptr')) ),
    '*.wcscspn':( 'int', None, 'cdecl', '*.wcscspn', (('void *', 'ptr'), ('int', None)) ),
    '*.wcslen':( 'int', None, 'cdecl', '*.wcslen', (('void *', 'ptr'),) ),
    '*.wcsncat':( 'int', None, 'cdecl', '*.wcsncat', (('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*.wcsncmp':( 'int', None, 'cdecl', '*.wcsncmp', (('int', None), ('int', None), ('int', None)) ),
    '*.wcsncpy':( 'int', None, 'cdecl', '*.wcsncpy', (('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*.wcspbrk':( 'int', None, 'cdecl', '*.wcspbrk', (('int', None), ('int', None)) ),
    '*.wcsrchr':( 'int', None, 'cdecl', '*.wcsrchr', (('int', None), ('int', None)) ),
    '*.wcsspn':( 'int', None, 'cdecl', '*.wcsspn', (('int', None), ('int', None)) ),
    '*.wcsstr':( 'int', None, 'cdecl', '*.wcsstr', (('void *', 'ptr'), ('int', None)) ),
    '*.wcstol':( 'int', None, 'cdecl', '*.wcstol', (('int', None), ('int', None), ('int', None)) ),
    '*.wcstombs':( 'int', None, 'cdecl', '*.wcstombs', (('int', None), ('void *', 'ptr'), ('int', None)) ),
    '*.wcstoul':( 'int', None, 'cdecl', '*.wcstoul', (('int', None), ('void *', 'ptr'), ('int', None)) ),

    '*._hread':( 'int', None, 'stdcall', '*._hread', (('int', None), ('void *', 'ptr'), ('int', None)) ),
    '*._hwrite':( 'int', None, 'stdcall', '*._hwrite', (('int', None), ('void *', 'ptr'), ('int', None)) ),
    '*._lclose':( 'int', None, 'stdcall', '*._lclose', (('int', None),) ),
    '*._lcreat':( 'int', None, 'stdcall', '*._lcreat', (('int', None), ('int', None)) ),
    '*._llseek':( 'int', None, 'stdcall', '*._llseek', (('int', None), ('int', None), ('int', None)) ),
    '*._lopen':( 'int', None, 'stdcall', '*._lopen', (('int', None), ('int', None)) ),
    '*._lread':( 'int', None, 'stdcall', '*._lread', (('int', None), ('void *', 'ptr'), ('int', None)) ),
    '*._lwrite':( 'int', None, 'stdcall', '*._lwrite', (('int', None), ('void *', 'ptr'), ('int', None)) ),
    '*.lstrcat':( 'int', None, 'stdcall', '*.lstrcat', (('int', None), ('int', None)) ),
    '*.lstrcata':( 'int', None, 'stdcall', '*.lstrcatA', (('int', None), ('int', None)) ),
    '*.lstrcatw':( 'int', None, 'stdcall', '*.lstrcatW', (('int', None), ('void *', 'ptr')) ),
    '*.lstrcmp':( 'int', None, 'stdcall', '*.lstrcmp', (('void *', 'ptr'), ('int', None)) ),
    '*.lstrcmpa':( 'int', None, 'stdcall', '*.lstrcmpA', (('void *', 'ptr'), ('int', None)) ),
    '*.lstrcmpw':( 'int', None, 'stdcall', '*.lstrcmpW', (('void *', 'ptr'), ('void *', 'ptr')) ),
    '*.lstrcmpi':( 'int', None, 'stdcall', '*.lstrcmpi', (('int', None), ('int', None)) ),
    '*.lstrcmpia':( 'int', None, 'stdcall', '*.lstrcmpiA', (('int', None), ('int', None)) ),
    '*.lstrcmpiw':( 'int', None, 'stdcall', '*.lstrcmpiW', (('int', None), ('int', None)) ),
    '*.lstrcpy':( 'int', None, 'stdcall', '*.lstrcpy', (('int', None), ('int', None)) ),
    '*.lstrcpya':( 'int', None, 'stdcall', '*.lstrcpyA', (('int', None), ('int', None)) ),
    '*.lstrcpyw':( 'int', None, 'stdcall', '*.lstrcpyW', (('int', None), ('int', None)) ),
    '*.lstrcpyn':( 'int', None, 'stdcall', '*.lstrcpyn', (('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*.lstrcpyna':( 'int', None, 'stdcall', '*.lstrcpynA', (('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*.lstrcpynw':( 'int', None, 'stdcall', '*.lstrcpynW', (('int', None), ('int', None), ('int', None)) ),
    '*.lstrlen':( 'int', None, 'stdcall', '*.lstrlen', (('int', None),) ),
    '*.lstrlena':( 'int', None, 'stdcall', '*.lstrlenA', (('int', None),) ),
    '*.lstrlenw':( 'int', None, 'stdcall', '*.lstrlenW', (('int', None),) ),

    '*._getdays':( 'int', None, 'cdecl', '*._Getdays', () ),
    '*._getmonths':( 'int', None, 'cdecl', '*._Getmonths', () ),
    '*._gettnames':( 'int', None, 'cdecl', '*._Gettnames', () ),
    '*._huge':( 'int', None, 'cdecl', '*._HUGE', () ),
    '*._strftime':( 'int', None, 'cdecl', '*._Strftime', (('void *', 'ptr'), ('int', None), ('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*._xcptfilter':( 'int', None, 'cdecl', '*._XcptFilter', (('int', None), ('int', None)) ),
    '*.__cppxcptfilter':( 'int', None, 'cdecl', '*.__CppXcptFilter', (('int', None), ('int', None)) ),
    '*.__cxxcallunwinddtor':( 'int', None, 'cdecl', '*.__CxxCallUnwindDtor', (('void *', 'funcptr'), ('int', None)) ),
    '*.__cxxcallunwindvecdtor':( 'int', None, 'cdecl', '*.__CxxCallUnwindVecDtor', (('void *', 'funcptr'), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*.__cxxdetectrethrow':( 'int', None, 'cdecl', '*.__CxxDetectRethrow', (('int', None),) ),
    '*.__cxxexceptionfilter':( 'int', None, 'cdecl', '*.__CxxExceptionFilter', (('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*.__cxxframehandler':( 'int', None, 'bfastcall', '*.__CxxFrameHandler', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*.__cxxlongjmpunwind':( 'int', None, 'stdcall', '*.__CxxLongjmpUnwind', (('int', None),) ),
    '*.__cxxqueryexceptionsize':( 'int', None, 'cdecl', '*.__CxxQueryExceptionSize', () ),
    '*.__cxxregisterexceptionobject':( 'int', None, 'cdecl', '*.__CxxRegisterExceptionObject', (('int', None), ('void *', 'ptr')) ),
    '*.__cxxunregisterexceptionobject':( 'int', None, 'cdecl', '*.__CxxUnregisterExceptionObject', (('int', None), ('int', None), ('int', None)) ),
    '*.__destructexceptionobject':( 'int', None, 'cdecl', '*.__DestructExceptionObject', (('int', None),) ),
    '*.__rtcasttovoid':( 'int', None, 'cdecl', '*.__RTCastToVoid', () ),
    '*.__rtdynamiccast':( 'int', None, 'cdecl', '*.__RTDynamicCast', ( ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*.__rttypeid':( 'int', None, 'cdecl', '*.__RTtypeid', (('int', None),) ),
    '*.__stringtold':( 'int', None, 'cdecl', '*.__STRINGTOLD', (('int', None), ('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*.___lc_codepage_func':( 'int', None, 'cdecl', '*.___lc_codepage_func', () ),
    '*.___lc_collate_cp_func':( 'int', None, 'cdecl', '*.___lc_collate_cp_func', () ),
    '*.___lc_handle_func':( 'int', None, 'cdecl', '*.___lc_handle_func', () ),
    '*.___mb_cur_max_func':( 'int', None, 'cdecl', '*.___mb_cur_max_func', () ),
    '*.___setlc_active_func':( 'int', None, 'cdecl', '*.___setlc_active_func', () ),
    '*.___unguarded_readlc_active_add_func':( 'int', None, 'cdecl', '*.___unguarded_readlc_active_add_func', () ),
    '*.__argc':( 'int', None, 'cdecl', '*.__argc', () ),
    '*.__argv':( 'int', None, 'cdecl', '*.__argv', () ),
    '*.__badioinfo':( 'int', None, 'cdecl', '*.__badioinfo', () ),
    '*.__buffer_overrun':( 'int', None, 'cdecl', '*.__buffer_overrun', () ),
    '*.__crtcomparestringa':( 'int', None, 'cdecl', '*.__crtCompareStringA', (('int', None), ('int', None), ('void *', 'ptr'), ('int', None), ('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*.__crtcomparestringw':( 'int', None, 'cdecl', '*.__crtCompareStringW', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*.__crtgetlocaleinfow':( 'int', None, 'cdecl', '*.__crtGetLocaleInfoW', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*.__crtgetstringtypew':( 'int', None, 'cdecl', '*.__crtGetStringTypeW', (('int', None), ('int', None), ('int', None), ('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*.__crtlcmapstringa':( 'int', None, 'cdecl', '*.__crtLCMapStringA', (('int', None), ('int', None), ('void *', 'ptr'), ('int', None), ('void *', 'ptr'), ('int', None), ('int', None), ('int', None)) ),
    '*.__crtlcmapstringw':( 'int', None, 'cdecl', '*.__crtLCMapStringW', (('int', None), ('int', None), ('int', None), ('int', None), ('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*.__dllonexit':( 'int', None, 'cdecl', '*.__dllonexit', (('int', None), ('int', None), ('int', None)) ),
    '*.__doserrno':( 'int', None, 'cdecl', '*.__doserrno', () ),
    '*.__fpecode':( 'int', None, 'cdecl', '*.__fpecode', () ),
    '*.__getmainargs':( 'int', None, 'cdecl', '*.__getmainargs', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*.__initenv':( 'int', None, 'cdecl', '*.__initenv', () ),
    '*.__iob_func':( 'int', None, 'cdecl', '*.__iob_func', () ),
    '*.__isascii':( 'int', None, 'cdecl', '*.__isascii', (('int', None),) ),
    '*.__iscsym':( 'int', None, 'cdecl', '*.__iscsym', (('int', None),) ),
    '*.__iscsymf':( 'int', None, 'cdecl', '*.__iscsymf', (('int', None),) ),
    '*.__lc_clike':( 'int', None, 'bfastcall', '*.__lc_clike', (('int', None),) ),
    '*.__lc_codepage':( 'int', None, 'cdecl', '*.__lc_codepage', () ),
    '*.__lc_collate_cp':( 'int', None, 'cdecl', '*.__lc_collate_cp', () ),
    '*.__lc_handle':( 'int', None, 'cdecl', '*.__lc_handle', () ),
    '*.__lconv_init':( 'int', None, 'cdecl', '*.__lconv_init', () ),
    '*.__mb_cur_max':( 'int', None, 'bfastcall', '*.__mb_cur_max', (('int', None),) ),
    '*.__p___argc':( 'int', None, 'cdecl', '*.__p___argc', () ),
    '*.__p___argv':( 'int', None, 'cdecl', '*.__p___argv', () ),
    '*.__p___initenv':( 'int', None, 'cdecl', '*.__p___initenv', () ),
    '*.__p___mb_cur_max':( 'int', None, 'cdecl', '*.__p___mb_cur_max', () ),
    '*.__p___wargv':( 'int', None, 'cdecl', '*.__p___wargv', () ),
    '*.__p___winitenv':( 'int', None, 'cdecl', '*.__p___winitenv', () ),
    '*.__p__acmdln':( 'int', None, 'cdecl', '*.__p__acmdln', () ),
    '*.__p__amblksiz':( 'int', None, 'cdecl', '*.__p__amblksiz', () ),
    '*.__p__commode':( 'int', None, 'cdecl', '*.__p__commode', () ),
    '*.__p__daylight':( 'int', None, 'cdecl', '*.__p__daylight', () ),
    '*.__p__dstbias':( 'int', None, 'cdecl', '*.__p__dstbias', () ),
    '*.__p__environ':( 'int', None, 'cdecl', '*.__p__environ', () ),
    '*.__p__fileinfo':( 'int', None, 'cdecl', '*.__p__fileinfo', () ),
    '*.__p__fmode':( 'int', None, 'cdecl', '*.__p__fmode', () ),
    '*.__p__iob':( 'int', None, 'cdecl', '*.__p__iob', () ),
    '*.__p__mbcasemap':( 'int', None, 'cdecl', '*.__p__mbcasemap', () ),
    '*.__p__mbctype':( 'int', None, 'cdecl', '*.__p__mbctype', () ),
    '*.__p__osver':( 'int', None, 'cdecl', '*.__p__osver', () ),
    '*.__p__pctype':( 'int', None, 'cdecl', '*.__p__pctype', () ),
    '*.__p__pgmptr':( 'int', None, 'cdecl', '*.__p__pgmptr', () ),
    '*.__p__pwctype':( 'int', None, 'cdecl', '*.__p__pwctype', () ),
    '*.__p__timezone':( 'int', None, 'cdecl', '*.__p__timezone', () ),
    '*.__p__tzname':( 'int', None, 'cdecl', '*.__p__tzname', () ),
    '*.__p__wcmdln':( 'int', None, 'cdecl', '*.__p__wcmdln', () ),
    '*.__p__wenviron':( 'int', None, 'cdecl', '*.__p__wenviron', () ),
    '*.__p__winmajor':( 'int', None, 'cdecl', '*.__p__winmajor', () ),
    '*.__p__winminor':( 'int', None, 'cdecl', '*.__p__winminor', () ),
    '*.__p__winver':( 'int', None, 'cdecl', '*.__p__winver', () ),
    '*.__p__wpgmptr':( 'int', None, 'cdecl', '*.__p__wpgmptr', () ),
    '*.__pctype_func':( 'int', None, 'cdecl', '*.__pctype_func', () ),
    '*.__pioinfo':( 'int', None, 'cdecl', '*.__pioinfo', () ),
    '*.__pwctype_func':( 'int', None, 'cdecl', '*.__pwctype_func', () ),
    '*.__pxcptinfoptrs':( 'int', None, 'cdecl', '*.__pxcptinfoptrs', () ),
    '*.__security_error_handler':( 'int', None, 'cdecl', '*.__security_error_handler', (('int', None), ('int', None)) ),
    '*.__set_app_type':( 'int', None, 'cdecl', '*.__set_app_type', (('int', None),) ),
    '*.__set_buffer_overrun_handler':( 'int', None, 'cdecl', '*.__set_buffer_overrun_handler', (('int', None),) ),
    '*.__setlc_active':( 'int', None, 'cdecl', '*.__setlc_active', () ),
    '*.__setusermatherr':( 'int', None, 'cdecl', '*.__setusermatherr', (('int', None),) ),
    '*.__threadhandle':( 'int', None, 'stdcall', '*.__threadhandle', () ),
    '*.__threadid':( 'int', None, 'stdcall', '*.__threadid', () ),
    '*.__toascii':( 'int', None, 'cdecl', '*.__toascii', (('int', None),) ),
    '*.__undname':( 'int', None, 'cdecl', '*.__unDName', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*.__undnameex':( 'int', None, 'cdecl', '*.__unDNameEx', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*.__uncaught_exception':( 'int', None, 'cdecl', '*.__uncaught_exception', () ),
    '*.__unguarded_readlc_active':( 'int', None, 'cdecl', '*.__unguarded_readlc_active', () ),
    '*.__wargv':( 'int', None, 'cdecl', '*.__wargv', () ),
    '*.__wcserror':( 'int', None, 'cdecl', '*.__wcserror', (('int', None),) ),
    '*.__wgetmainargs':( 'int', None, 'msfastcall', '*.__wgetmainargs', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*.__winitenv':( 'int', None, 'cdecl', '*.__winitenv', () ),
    '*._abnormal_termination':( 'int', None, 'cdecl', '*._abnormal_termination', () ),
    '*._access':( 'int', None, 'cdecl', '*._access', (('void *', 'ptr'), ('int', None)) ),
    '*._acmdln':( 'int', None, 'cdecl', '*._acmdln', () ),
    '*._adj_fdiv_m16i':( 'int', None, 'cdecl', '*._adj_fdiv_m16i', () ),
    '*._adj_fdiv_m32':( 'int', None, 'cdecl', '*._adj_fdiv_m32', (('int', None),) ),
    '*._adj_fdiv_m32i':( 'int', None, 'cdecl', '*._adj_fdiv_m32i', () ),
    '*._adj_fdiv_m64':( 'int', None, 'cdecl', '*._adj_fdiv_m64', (('int', None), ('int', None)) ),
    '*._adj_fdiv_r':( 'int', None, 'cdecl', '*._adj_fdiv_r', () ),
    '*._adj_fdivr_m16i':( 'int', None, 'cdecl', '*._adj_fdivr_m16i', () ),
    '*._adj_fdivr_m32':( 'int', None, 'cdecl', '*._adj_fdivr_m32', (('int', None),) ),
    '*._adj_fdivr_m32i':( 'int', None, 'cdecl', '*._adj_fdivr_m32i', () ),
    '*._adj_fdivr_m64':( 'int', None, 'cdecl', '*._adj_fdivr_m64', (('int', None), ('int', None)) ),
    '*._adj_fpatan':( 'int', None, 'cdecl', '*._adj_fpatan', () ),
    '*._adj_fprem':( 'int', None, 'cdecl', '*._adj_fprem', () ),
    '*._adj_fprem1':( 'int', None, 'cdecl', '*._adj_fprem1', () ),
    '*._adj_fptan':( 'int', None, 'cdecl', '*._adj_fptan', () ),
    '*._adjust_fdiv':( 'int', None, 'cdecl', '*._adjust_fdiv', () ),
    '*._aexit_rtn':( 'int', None, 'cdecl', '*._aexit_rtn', () ),
    '*._aligned_free':( 'int', None, 'cdecl', '*._aligned_free', (('int', None),) ),
    '*._aligned_malloc':( 'int', None, 'cdecl', '*._aligned_malloc', (('int', None), ('int', None)) ),
    '*._aligned_offset_malloc':( 'int', None, 'cdecl', '*._aligned_offset_malloc', (('int', None), ('int', None), ('int', None)) ),
    '*._aligned_offset_realloc':( 'int', None, 'cdecl', '*._aligned_offset_realloc', (('void *', 'ptr'), ('int', None), ('int', None), ('int', None)) ),
    '*._aligned_realloc':( 'int', None, 'cdecl', '*._aligned_realloc', (('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*._amsg_exit':( 'int', None, 'cdecl', '*._amsg_exit', (('int', None),) ),
    '*._assert':( 'int', None, 'stdcall', '*._assert', (('void *', 'ptr'),) ),
    '*._atodbl':( 'int', None, 'cdecl', '*._atodbl', (('void *', 'ptr'), ('int', None)) ),
    '*._atoi64':( 'int', None, 'cdecl', '*._atoi64', (('int', None),) ),
    '*._atoldbl':( 'int', None, 'cdecl', '*._atoldbl', (('int', None), ('int', None)) ),
    '*._beep':( 'int', None, 'cdecl', '*._beep', (('int', None), ('int', None)) ),
    '*._beginthread':( 'int', None, 'cdecl', '*._beginthread', (('int', None), ('int', None), ('int', None)) ),
    '*._beginthreadex':( 'int', None, 'cdecl', '*._beginthreadex', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._c_exit':( 'int', None, 'cdecl', '*._c_exit', () ),
    '*._cabs':( 'int', None, 'cdecl', '*._cabs', () ),
    '*._callnewh':( 'int', None, 'cdecl', '*._callnewh', (('int', None),) ),
    '*._cexit':( 'int', None, 'cdecl', '*._cexit', () ),
    '*._cgets':( 'int', None, 'cdecl', '*._cgets', (('int', None),) ),
    '*._cgetws':( 'int', None, 'cdecl', '*._cgetws', (('int', None),) ),
    '*._chdir':( 'int', None, 'cdecl', '*._chdir', (('int', None),) ),
    '*._chdrive':( 'int', None, 'cdecl', '*._chdrive', (('int', None),) ),
    '*._chgsign':( 'int', None, 'cdecl', '*._chgsign', (('int', None), ('int', None)) ),
    '*._chkesp':( 'int', None, 'cdecl', '*._chkesp', () ),
    '*._chmod':( 'int', None, 'cdecl', '*._chmod', (('int', None), ('int', None)) ),
    '*._chsize':( 'int', None, 'cdecl', '*._chsize', (('int', None), ('int', None)) ),
    '*._clearfp':( 'int', None, 'cdecl', '*._clearfp', () ),
    '*._close':( 'int', None, 'cdecl', '*._close', (('int', None),) ),
    '*._commit':( 'int', None, 'cdecl', '*._commit', (('int', None),) ),
    '*._commode':( 'int', None, 'cdecl', '*._commode', () ),
    '*._control87':( 'int', None, 'cdecl', '*._control87', () ),
    '*._controlfp':( 'int', None, 'cdecl', '*._controlfp', (('int', None), ('int', None)) ),
    '*._copysign':( 'int', None, 'cdecl', '*._copysign', (('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._cprintf':( 'int', None, 'cdecl', '*._cprintf', (('int', None),) ),
    '*._cputs':( 'int', None, 'cdecl', '*._cputs', (('void *', 'ptr'),) ),
    '*._cputws':( 'int', None, 'cdecl', '*._cputws', (('void *', 'ptr'),) ),
    '*._creat':( 'int', None, 'cdecl', '*._creat', (('StringA', None), ('int', None)) ),
    '*._cscanf':( 'int', None, 'cdecl', '*._cscanf', (('int', None),) ),
    '*._ctime64':( 'int', None, 'cdecl', '*._ctime64', (('void *', 'ptr'),) ),
    '*._cwait':( 'int', None, 'cdecl', '*._cwait', (('void *', 'ptr'), ('HANDLE', None)) ),
    '*._cwprintf':( 'int', None, 'cdecl', '*._cwprintf', (('int', None),) ),
    '*._cwscanf':( 'int', None, 'cdecl', '*._cwscanf', (('int', None),) ),
    '*._daylight':( 'int', None, 'bfastcall', '*._daylight', (('int', None),) ),
    '*._dstbias':( 'int', None, 'cdecl', '*._dstbias', () ),
    '*._dup':( 'int', None, 'cdecl', '*._dup', (('int', None),) ),
    '*._dup2':( 'int', None, 'cdecl', '*._dup2', (('int', None), ('int', None)) ),
    '*._ecvt':( 'int', None, 'cdecl', '*._ecvt', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._endthread':( 'int', None, 'cdecl', '*._endthread', () ),
    '*._endthreadex':( 'int', None, 'cdecl', '*._endthreadex', (('int', None),) ),
    '*._environ':( 'int', None, 'cdecl', '*._environ', () ),
    '*._eof':( 'int', None, 'cdecl', '*._eof', (('int', None),) ),
    '*._errno':( 'int', None, 'cdecl', '*._errno', () ),
    '*._except_handler2':( 'int', None, 'cdecl', '*._except_handler2', (('int', None), ('void *', 'ptr'), ('int', None)) ),
    '*._except_handler3':( 'int', None, 'cdecl', '*._except_handler3', (('int', None), ('void *', 'ptr'), ('int', None)) ),
    '*._execl':( 'int', None, 'cdecl', '*._execl', () ),
    '*._execle':( 'int', None, 'cdecl', '*._execle', ( ('int', None), ('int', None)) ),
    '*._execlp':( 'int', None, 'cdecl', '*._execlp', () ),
    '*._execlpe':( 'int', None, 'cdecl', '*._execlpe', ( ('int', None), ('int', None)) ),
    '*._execv':( 'int', None, 'cdecl', '*._execv', ( ('int', None),) ),
    '*._execve':( 'int', None, 'cdecl', '*._execve', ( ('int', None), ('int', None)) ),
    '*._execvp':( 'int', None, 'cdecl', '*._execvp', ( ('int', None),) ),
    '*._execvpe':( 'int', None, 'cdecl', '*._execvpe', ( ('int', None), ('int', None)) ),
    '*._exit':( 'int', None, 'cdecl', '*._exit', (('int', None),) ),
    '*._expand':( 'int', None, 'cdecl', '*._expand', (('int', None), ('int', None)) ),
    '*._fcloseall':( 'int', None, 'cdecl', '*._fcloseall', () ),
    '*._fcvt':( 'int', None, 'cdecl', '*._fcvt', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._fdopen':( 'int', None, 'cdecl', '*._fdopen', (('int', None), ('int', None)) ),
    '*._fgetchar':( 'int', None, 'cdecl', '*._fgetchar', () ),
    '*._fgetwchar':( 'int', None, 'cdecl', '*._fgetwchar', () ),
    '*._filbuf':( 'int', None, 'cdecl', '*._filbuf', (('int', None),) ),
    '*._fileinfo':( 'int', None, 'cdecl', '*._fileinfo', () ),
    '*._filelength':( 'int', None, 'cdecl', '*._filelength', (('int', None),) ),
    '*._filelengthi64':( 'int', None, 'cdecl', '*._filelengthi64', (('int', None),) ),
    '*._fileno':( 'int', None, 'cdecl', '*._fileno', (('int', None),) ),
    '*._findclose':( 'int', None, 'cdecl', '*._findclose', (('void *', 'ptr'),) ),
    '*._findfirst':( 'int', None, 'cdecl', '*._findfirst', (('int', None), ('void *', 'ptr')) ),
    '*._findfirst64':( 'int', None, 'cdecl', '*._findfirst64', (('int', None), ('void *', 'ptr')) ),
    '*._findfirsti64':( 'int', None, 'cdecl', '*._findfirsti64', (('int', None), ('void *', 'ptr')) ),
    '*._findnext':( 'int', None, 'cdecl', '*._findnext', (('int', None), ('void *', 'ptr')) ),
    '*._findnext64':( 'int', None, 'cdecl', '*._findnext64', (('int', None), ('void *', 'ptr')) ),
    '*._findnexti64':( 'int', None, 'cdecl', '*._findnexti64', (('int', None), ('void *', 'ptr')) ),
    '*._finite':( 'int', None, 'cdecl', '*._finite', (('int', None), ('int', None)) ),
    '*._flsbuf':( 'int', None, 'cdecl', '*._flsbuf', (('int', None), ('void *', 'ptr')) ),
    '*._flushall':( 'int', None, 'cdecl', '*._flushall', () ),
    '*._fmode':( 'int', None, 'cdecl', '*._fmode', () ),
    '*._fpclass':( 'int', None, 'cdecl', '*._fpclass', (('int', None), ('int', None)) ),
    '*._fpieee_flt':( 'int', None, 'cdecl', '*._fpieee_flt', (('int', None),) ),
    '*._fpreset':( 'int', None, 'cdecl', '*._fpreset', () ),
    '*._fputchar':( 'int', None, 'cdecl', '*._fputchar', (('int', None),) ),
    '*._fputwchar':( 'int', None, 'cdecl', '*._fputwchar', (('int', None),) ),
    '*._fsopen':( 'int', None, 'cdecl', '*._fsopen', (('StringA', None), ('int', None), ('int', None)) ),
    '*._fstat':( 'int', None, 'cdecl', '*._fstat', (('int', None), ('int', None)) ),
    '*._fstat64':( 'int', None, 'cdecl', '*._fstat64', (('int', None), ('int', None)) ),
    '*._fstati64':( 'int', None, 'cdecl', '*._fstati64', (('int', None), ('int', None)) ),
    '*._ftime':( 'int', None, 'cdecl', '*._ftime', (('int', None),) ),
    '*._ftime64':( 'int', None, 'cdecl', '*._ftime64', (('int', None),) ),
    '*._ftol':( 'int', None, 'cdecl', '*._ftol', () ),
    '*._fullpath':( 'int', None, 'cdecl', '*._fullpath', (('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*._futime':( 'int', None, 'cdecl', '*._futime', (('int', None), ('void *', 'ptr')) ),
    '*._futime64':( 'int', None, 'cdecl', '*._futime64', (('int', None), ('void *', 'ptr')) ),
    '*._gcvt':( 'int', None, 'cdecl', '*._gcvt', (('int', None), ('int', None), ('int', None), ('void *', 'ptr')) ),
    '*._get_heap_handle':( 'int', None, 'cdecl', '*._get_heap_handle', () ),
    '*._get_osfhandle':( 'int', None, 'cdecl', '*._get_osfhandle', (('int', None),) ),
    '*._get_sbh_threshold':( 'int', None, 'cdecl', '*._get_sbh_threshold', () ),
    '*._getch':( 'int', None, 'cdecl', '*._getch', () ),
    '*._getche':( 'int', None, 'cdecl', '*._getche', () ),
    '*._getcwd':( 'int', None, 'cdecl', '*._getcwd', (('void *', 'ptr'), ('int', None)) ),
    '*._getdcwd':( 'int', None, 'cdecl', '*._getdcwd', (('int', None), ('void *', 'ptr'), ('int', None)) ),
    '*._getdiskfree':( 'int', None, 'cdecl', '*._getdiskfree', (('int', None), ('int', None)) ),
    '*._getdllprocaddr':( 'int', None, 'cdecl', '*._getdllprocaddr', (('HMODULE', None), ('StringA', None), ('int', None)) ),
    '*._getdrive':( 'int', None, 'cdecl', '*._getdrive', () ),
    '*._getdrives':( 'int', None, 'stdcall', '*._getdrives', () ),
    '*._getmaxstdio':( 'int', None, 'cdecl', '*._getmaxstdio', () ),
    '*._getmbcp':( 'int', None, 'cdecl', '*._getmbcp', () ),
    '*._getpid':( 'int', None, 'stdcall', '*._getpid', () ),
    '*._getsystime':( 'int', None, 'cdecl', '*._getsystime', (('int', None),) ),
    '*._getw':( 'int', None, 'cdecl', '*._getw', (('int', None),) ),
    '*._getwch':( 'int', None, 'cdecl', '*._getwch', () ),
    '*._getwche':( 'int', None, 'cdecl', '*._getwche', () ),
    '*._getws':( 'int', None, 'cdecl', '*._getws', (('int', None),) ),
    '*._global_unwind2':( 'int', None, 'cdecl', '*._global_unwind2', (('int', None),) ),
    '*._gmtime64':( 'int', None, 'cdecl', '*._gmtime64', (('void *', 'ptr'),) ),
    '*._heapadd':( 'int', None, 'cdecl', '*._heapadd', () ),
    '*._heapchk':( 'int', None, 'cdecl', '*._heapchk', () ),
    '*._heapmin':( 'int', None, 'cdecl', '*._heapmin', () ),
    '*._heapset':( 'int', None, 'cdecl', '*._heapset', () ),
    '*._heapused':( 'int', None, 'cdecl', '*._heapused', () ),
    '*._heapwalk':( 'int', None, 'cdecl', '*._heapwalk', (('int', None),) ),
    '*._hypot':( 'int', None, 'cdecl', '*._hypot', () ),
    '*._i64toa':( 'int', None, 'msfastcall', '*._i64toa', (('int', None), ('int', None), ('int', None), ('int', None), ('void *', 'ptr'), ('int', None)) ),
    '*._i64tow':( 'int', None, 'msfastcall', '*._i64tow', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._initterm':( 'int', None, 'cdecl', '*._initterm', (('int', None), ('int', None)) ),
    '*._inp':( 'int', None, 'cdecl', '*._inp', (('int', None),) ),
    '*._inpd':( 'int', None, 'cdecl', '*._inpd', (('int', None),) ),
    '*._inpw':( 'int', None, 'cdecl', '*._inpw', (('int', None),) ),
    '*._iob':( 'int', None, 'bfastcall', '*._iob', (('int', None),) ),
    '*._isatty':( 'int', None, 'cdecl', '*._isatty', (('int', None),) ),
    '*._isctype':( 'int', None, 'cdecl', '*._isctype', (('int', None), ('int', None)) ),
    '*._ismbbalnum':( 'int', None, 'cdecl', '*._ismbbalnum', (('int', None),) ),
    '*._ismbbalpha':( 'int', None, 'cdecl', '*._ismbbalpha', (('int', None),) ),
    '*._ismbbgraph':( 'int', None, 'cdecl', '*._ismbbgraph', (('int', None),) ),
    '*._ismbbkalnum':( 'int', None, 'cdecl', '*._ismbbkalnum', (('int', None),) ),
    '*._ismbbkana':( 'int', None, 'cdecl', '*._ismbbkana', (('int', None),) ),
    '*._ismbbkprint':( 'int', None, 'cdecl', '*._ismbbkprint', (('int', None),) ),
    '*._ismbbkpunct':( 'int', None, 'cdecl', '*._ismbbkpunct', (('int', None),) ),
    '*._ismbblead':( 'int', None, 'cdecl', '*._ismbblead', (('int', None),) ),
    '*._ismbbprint':( 'int', None, 'cdecl', '*._ismbbprint', (('int', None),) ),
    '*._ismbbpunct':( 'int', None, 'cdecl', '*._ismbbpunct', (('int', None),) ),
    '*._ismbbtrail':( 'int', None, 'cdecl', '*._ismbbtrail', (('int', None),) ),
    '*._ismbcalnum':( 'int', None, 'cdecl', '*._ismbcalnum', (('int', None),) ),
    '*._ismbcalpha':( 'int', None, 'cdecl', '*._ismbcalpha', (('int', None),) ),
    '*._ismbcdigit':( 'int', None, 'cdecl', '*._ismbcdigit', (('int', None),) ),
    '*._ismbcgraph':( 'int', None, 'cdecl', '*._ismbcgraph', (('int', None),) ),
    '*._ismbchira':( 'int', None, 'cdecl', '*._ismbchira', (('int', None),) ),
    '*._ismbckata':( 'int', None, 'cdecl', '*._ismbckata', (('int', None),) ),
    '*._ismbcl0':( 'int', None, 'cdecl', '*._ismbcl0', (('int', None),) ),
    '*._ismbcl1':( 'int', None, 'cdecl', '*._ismbcl1', (('int', None),) ),
    '*._ismbcl2':( 'int', None, 'cdecl', '*._ismbcl2', (('int', None),) ),
    '*._ismbclegal':( 'int', None, 'cdecl', '*._ismbclegal', (('int', None),) ),
    '*._ismbclower':( 'int', None, 'cdecl', '*._ismbclower', (('int', None),) ),
    '*._ismbcprint':( 'int', None, 'cdecl', '*._ismbcprint', (('int', None),) ),
    '*._ismbcpunct':( 'int', None, 'cdecl', '*._ismbcpunct', (('int', None),) ),
    '*._ismbcspace':( 'int', None, 'cdecl', '*._ismbcspace', (('int', None),) ),
    '*._ismbcsymbol':( 'int', None, 'cdecl', '*._ismbcsymbol', (('int', None),) ),
    '*._ismbcupper':( 'int', None, 'cdecl', '*._ismbcupper', (('int', None),) ),
    '*._ismbslead':( 'int', None, 'cdecl', '*._ismbslead', (('int', None), ('int', None)) ),
    '*._ismbstrail':( 'int', None, 'cdecl', '*._ismbstrail', (('int', None), ('int', None)) ),
    '*._isnan':( 'int', None, 'cdecl', '*._isnan', (('int', None), ('int', None)) ),
    '*._itoa':( 'int', None, 'cdecl', '*._itoa', (('int', None), ('void *', 'obj'), ('int', None)) ),
    '*._itow':( 'int', None, 'cdecl', '*._itow', (('int', None), ('int', None), ('int', None)) ),
    '*._j0':( 'int', None, 'cdecl', '*._j0', () ),
    '*._j1':( 'int', None, 'cdecl', '*._j1', () ),
    '*._jn':( 'int', None, 'cdecl', '*._jn', (('int', None),) ),
    '*._kbhit':( 'int', None, 'cdecl', '*._kbhit', () ),
    '*._lfind':( 'int', None, 'cdecl', '*._lfind', (('int', None), ('int', None), ('int', None), ('int', None), ('void *', 'funcptr')) ),
    '*._loaddll':( 'int', None, 'cdecl', '*._loaddll', (('FileNameA', None),) ),
    '*._local_unwind2':( 'int', None, 'cdecl', '*._local_unwind2', (('void *', 'ptr'), ('int', None)) ),
    '*._localtime64':( 'int', None, 'cdecl', '*._localtime64', (('void *', 'ptr'),) ),
    '*._lock':( 'int', None, 'cdecl', '*._lock', (('int', None),) ),
    '*._locking':( 'int', None, 'cdecl', '*._locking', (('int', None), ('int', None), ('int', None)) ),
    '*._logb':( 'int', None, 'cdecl', '*._logb', (('int', None), ('int', None)) ),
    '*._longjmpex':( 'int', None, 'cdecl', '*._longjmpex', (('int', None), ('int', None)) ),
    '*._lrotl':( 'int', None, 'cdecl', '*._lrotl', (('int', None), ('int', None)) ),
    '*._lrotr':( 'int', None, 'cdecl', '*._lrotr', (('int', None), ('int', None)) ),
    '*._lsearch':( 'int', None, 'cdecl', '*._lsearch', (('void *', 'ptr'), ('void *', 'ptr'), ('int', None), ('int', None), ('void *', 'funcptr')) ),
    '*._lseek':( 'int', None, 'cdecl', '*._lseek', (('int', None), ('int', None), ('int', None)) ),
    '*._lseeki64':( 'int', None, 'cdecl', '*._lseeki64', (('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._ltoa':( 'int', None, 'cdecl', '*._ltoa', (('int', None), ('void *', 'obj'), ('int', None)) ),
    '*._ltow':( 'int', None, 'cdecl', '*._ltow', (('int', None), ('int', None), ('int', None)) ),
    '*._makepath':( 'int', None, 'cdecl', '*._makepath', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._mbbtombc':( 'int', None, 'cdecl', '*._mbbtombc', (('int', None),) ),
    '*._mbbtype':( 'int', None, 'cdecl', '*._mbbtype', (('int', None), ('int', None)) ),
    '*._mbcasemap':( 'int', None, 'cdecl', '*._mbcasemap', () ),
    '*._mbccpy':( 'int', None, 'cdecl', '*._mbccpy', (('int', None), ('int', None)) ),
    '*._mbcjistojms':( 'int', None, 'cdecl', '*._mbcjistojms', (('int', None),) ),
    '*._mbcjmstojis':( 'int', None, 'cdecl', '*._mbcjmstojis', (('int', None),) ),
    '*._mbclen':( 'int', None, 'cdecl', '*._mbclen', (('int', None),) ),
    '*._mbctohira':( 'int', None, 'cdecl', '*._mbctohira', (('int', None),) ),
    '*._mbctokata':( 'int', None, 'cdecl', '*._mbctokata', (('int', None),) ),
    '*._mbctolower':( 'int', None, 'cdecl', '*._mbctolower', (('int', None),) ),
    '*._mbctombb':( 'int', None, 'cdecl', '*._mbctombb', (('int', None),) ),
    '*._mbctoupper':( 'int', None, 'cdecl', '*._mbctoupper', (('int', None),) ),
    '*._mbctype':( 'int', None, 'cdecl', '*._mbctype', () ),
    '*._mbsbtype':( 'int', None, 'cdecl', '*._mbsbtype', (('int', None), ('int', None)) ),
    '*._mbscat':( 'int', None, 'cdecl', '*._mbscat', (('void *', 'ptr'), ('void *', 'ptr')) ),
    '*._mbschr':( 'int', None, 'cdecl', '*._mbschr', (('int', None), ('int', None)) ),
    '*._mbscmp':( 'int', None, 'cdecl', '*._mbscmp', (('int', None), ('int', None)) ),
    '*._mbscoll':( 'int', None, 'cdecl', '*._mbscoll', (('void *', 'ptr'), ('void *', 'ptr')) ),
    '*._mbscpy':( 'int', None, 'cdecl', '*._mbscpy', (('void *', 'ptr'), ('void *', 'ptr')) ),
    '*._mbscspn':( 'int', None, 'cdecl', '*._mbscspn', (('int', None), ('int', None)) ),
    '*._mbsdec':( 'int', None, 'cdecl', '*._mbsdec', (('int', None), ('int', None)) ),
    '*._mbsdup':( 'int', None, 'cdecl', '*._mbsdup', (('void *', 'ptr'),) ),
    '*._mbsicmp':( 'int', None, 'cdecl', '*._mbsicmp', (('void *', 'ptr'), ('void *', 'ptr')) ),
    '*._mbsicoll':( 'int', None, 'cdecl', '*._mbsicoll', (('void *', 'ptr'), ('void *', 'ptr')) ),
    '*._mbsinc':( 'int', None, 'cdecl', '*._mbsinc', (('int', None),) ),
    '*._mbslen':( 'int', None, 'cdecl', '*._mbslen', (('int', None),) ),
    '*._mbslwr':( 'int', None, 'cdecl', '*._mbslwr', (('void *', 'ptr'),) ),
    '*._mbsnbcat':( 'int', None, 'cdecl', '*._mbsnbcat', (('int', None), ('int', None), ('int', None)) ),
    '*._mbsnbcmp':( 'int', None, 'cdecl', '*._mbsnbcmp', (('int', None), ('int', None), ('int', None)) ),
    '*._mbsnbcnt':( 'int', None, 'cdecl', '*._mbsnbcnt', (('int', None), ('int', None)) ),
    '*._mbsnbcoll':( 'int', None, 'cdecl', '*._mbsnbcoll', (('void *', 'ptr'), ('void *', 'ptr'), ('int', None)) ),
    '*._mbsnbcpy':( 'int', None, 'cdecl', '*._mbsnbcpy', (('int', None), ('void *', 'ptr'), ('int', None)) ),
    '*._mbsnbicmp':( 'int', None, 'cdecl', '*._mbsnbicmp', (('int', None), ('int', None), ('int', None)) ),
    '*._mbsnbicoll':( 'int', None, 'cdecl', '*._mbsnbicoll', (('void *', 'ptr'), ('void *', 'ptr'), ('int', None)) ),
    '*._mbsnbset':( 'int', None, 'cdecl', '*._mbsnbset', (('int', None), ('int', None), ('int', None)) ),
    '*._mbsncat':( 'int', None, 'cdecl', '*._mbsncat', (('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*._mbsnccnt':( 'int', None, 'cdecl', '*._mbsnccnt', (('int', None), ('int', None)) ),
    '*._mbsncmp':( 'int', None, 'cdecl', '*._mbsncmp', (('int', None), ('int', None), ('int', None)) ),
    '*._mbsncoll':( 'int', None, 'cdecl', '*._mbsncoll', (('void *', 'ptr'), ('void *', 'ptr'), ('int', None)) ),
    '*._mbsncpy':( 'int', None, 'cdecl', '*._mbsncpy', (('int', None), ('void *', 'ptr'), ('int', None)) ),
    '*._mbsnextc':( 'int', None, 'cdecl', '*._mbsnextc', (('int', None),) ),
    '*._mbsnicmp':( 'int', None, 'cdecl', '*._mbsnicmp', (('int', None), ('int', None), ('int', None)) ),
    '*._mbsnicoll':( 'int', None, 'cdecl', '*._mbsnicoll', (('void *', 'ptr'), ('void *', 'ptr'), ('int', None)) ),
    '*._mbsninc':( 'int', None, 'cdecl', '*._mbsninc', (('int', None), ('int', None)) ),
    '*._mbsnset':( 'int', None, 'cdecl', '*._mbsnset', (('int', None), ('int', None), ('int', None)) ),
    '*._mbspbrk':( 'int', None, 'cdecl', '*._mbspbrk', (('int', None), ('int', None)) ),
    '*._mbsrchr':( 'int', None, 'cdecl', '*._mbsrchr', (('int', None), ('int', None)) ),
    '*._mbsrev':( 'int', None, 'cdecl', '*._mbsrev', (('int', None),) ),
    '*._mbsset':( 'int', None, 'cdecl', '*._mbsset', (('int', None), ('int', None)) ),
    '*._mbsspn':( 'int', None, 'cdecl', '*._mbsspn', (('int', None), ('int', None)) ),
    '*._mbsspnp':( 'int', None, 'cdecl', '*._mbsspnp', (('int', None), ('int', None)) ),
    '*._mbsstr':( 'int', None, 'cdecl', '*._mbsstr', (('void *', 'ptr'), ('void *', 'ptr')) ),
    '*._mbstok':( 'int', None, 'cdecl', '*._mbstok', (('int', None), ('int', None)) ),
    '*._mbstrlen':( 'int', None, 'cdecl', '*._mbstrlen', (('int', None),) ),
    '*._mbsupr':( 'int', None, 'cdecl', '*._mbsupr', (('void *', 'ptr'),) ),
    '*._memccpy':( 'int', None, 'cdecl', '*._memccpy', (('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._memicmp':( 'int', None, 'cdecl', '*._memicmp', (('int', None), ('int', None), ('int', None)) ),
    '*._mkdir':( 'int', None, 'cdecl', '*._mkdir', (('StringA', None),) ),
    '*._mktemp':( 'int', None, 'cdecl', '*._mktemp', (('void *', 'ptr'),) ),
    '*._mktime64':( 'int', None, 'cdecl', '*._mktime64', (('int', None),) ),
    '*._msize':( 'int', None, 'cdecl', '*._msize', (('int', None),) ),
    '*._nextafter':( 'int', None, 'cdecl', '*._nextafter', (('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._onexit':( 'int', None, 'cdecl', '*._onexit', (('int', None),) ),
    '*._open':( 'int', None, 'cdecl', '*._open', (('StringA', None), ('int', None), ('int', None)) ),
    '*._open_osfhandle':( 'int', None, 'cdecl', '*._open_osfhandle', (('int', None), ('int', None)) ),
    '*._osplatform':( 'int', None, 'cdecl', '*._osplatform', () ),
    '*._osver':( 'int', None, 'cdecl', '*._osver', () ),
    '*._outp':( 'int', None, 'cdecl', '*._outp', (('int', None), ('int', None)) ),
    '*._outpd':( 'int', None, 'cdecl', '*._outpd', (('int', None), ('int', None)) ),
    '*._outpw':( 'int', None, 'cdecl', '*._outpw', (('int', None), ('int', None)) ),
    '*._pclose':( 'int', None, 'cdecl', '*._pclose', (('int', None),) ),
    '*._pctype':( 'int', None, 'cdecl', '*._pctype', () ),
    '*._pgmptr':( 'int', None, 'cdecl', '*._pgmptr', () ),
    '*._pipe':( 'int', None, 'cdecl', '*._pipe', (('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*._popen':( 'int', None, 'cdecl', '*._popen', (('void *', 'ptr'), ('int', None)) ),
    '*._purecall':( 'int', None, 'cdecl', '*._purecall', () ),
    '*._putch':( 'int', None, 'cdecl', '*._putch', (('int', None),) ),
    '*._putenv':( 'int', None, 'cdecl', '*._putenv', (('void *', 'ptr'),) ),
    '*._putw':( 'int', None, 'cdecl', '*._putw', (('int', None), ('void *', 'ptr')) ),
    '*._putwch':( 'int', None, 'cdecl', '*._putwch', (('int', None),) ),
    '*._putws':( 'int', None, 'cdecl', '*._putws', (('int', None),) ),
    '*._pwctype':( 'int', None, 'cdecl', '*._pwctype', () ),
    '*._read':( 'int', None, 'cdecl', '*._read', (('int', None), ('StringA', None), ('DWORD', None)) ),
    '*._resetstkoflw':( 'int', None, 'cdecl', '*._resetstkoflw', () ),
    '*._rmdir':( 'int', None, 'cdecl', '*._rmdir', (('int', None),) ),
    '*._rmtmp':( 'int', None, 'cdecl', '*._rmtmp', () ),
    '*._rotl':( 'int', None, 'cdecl', '*._rotl', (('int', None), ('int', None)) ),
    '*._rotr':( 'int', None, 'cdecl', '*._rotr', (('int', None), ('int', None)) ),
    '*._safe_fdiv':( 'int', None, 'cdecl', '*._safe_fdiv', () ),
    '*._safe_fdivr':( 'int', None, 'cdecl', '*._safe_fdivr', () ),
    '*._safe_fprem':( 'int', None, 'cdecl', '*._safe_fprem', () ),
    '*._safe_fprem1':( 'int', None, 'cdecl', '*._safe_fprem1', () ),
    '*._scalb':( 'int', None, 'cdecl', '*._scalb', (('int', None), ('int', None), ('int', None)) ),
    '*._scprintf':( 'int', None, 'cdecl', '*._scprintf', (('int', None),) ),
    '*._scwprintf':( 'int', None, 'cdecl', '*._scwprintf', (('int', None),) ),
    '*._searchenv':( 'int', None, 'cdecl', '*._searchenv', (('void *', 'ptr'), ('void *', 'ptr'), ('void *', 'ptr')) ),
    '*._seh_longjmp_unwind':( 'int', None, 'stdcall', '*._seh_longjmp_unwind', (('int', None),) ),
    '*._set_sse2_enable':( 'int', None, 'cdecl', '*._set_SSE2_enable', (('int', None),) ),
    '*._set_error_mode':( 'int', None, 'cdecl', '*._set_error_mode', (('int', None),) ),
    '*._set_purecall_handler':( 'int', None, 'cdecl', '*._set_purecall_handler', (('int', None),) ),
    '*._set_sbh_threshold':( 'int', None, 'cdecl', '*._set_sbh_threshold', (('int', None),) ),
    '*._set_security_error_handler':( 'int', None, 'cdecl', '*._set_security_error_handler', (('int', None),) ),
    '*._seterrormode':( 'int', None, 'cdecl', '*._seterrormode', (('int', None),) ),
    '*._setjmp':( 'int', None, 'cdecl', '*._setjmp', (('int', None),) ),
    '*._setjmp3':( 'int', None, 'cdecl', '*._setjmp3', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._setmaxstdio':( 'int', None, 'cdecl', '*._setmaxstdio', (('int', None),) ),
    '*._setmbcp':( 'int', None, 'cdecl', '*._setmbcp', (('int', None),) ),
    '*._setmode':( 'int', None, 'cdecl', '*._setmode', (('int', None), ('int', None)) ),
    '*._setsystime':( 'int', None, 'cdecl', '*._setsystime', (('int', None), ('int', None)) ),
    '*._sleep':( 'int', None, 'cdecl', '*._sleep', (('int', None),) ),
    '*._snprintf':( 'int', None, 'cdecl', '*._snprintf', (('int', None), ('int', None), ('int', None)) ),
    '*._snscanf':( 'int', None, 'cdecl', '*._snscanf', (('int', None), ('int', None), ('int', None)) ),
    '*._snwprintf':( 'int', None, 'cdecl', '*._snwprintf', (('int', None), ('int', None), ('int', None)) ),
    '*._snwscanf':( 'int', None, 'cdecl', '*._snwscanf', (('int', None), ('int', None), ('int', None)) ),
    '*._sopen':( 'int', None, 'cdecl', '*._sopen', (('StringA', None), ('int', None), ('int', None), ('int', None)) ),
    '*._spawnl':( 'int', None, 'cdecl', '*._spawnl', (('int', None), ('void *', 'obj')) ),
    '*._spawnle':( 'int', None, 'cdecl', '*._spawnle', (('int', None), ('void *', 'obj'), ('int', None), ('int', None)) ),
    '*._spawnlp':( 'int', None, 'cdecl', '*._spawnlp', (('int', None), ('void *', 'obj')) ),
    '*._spawnlpe':( 'int', None, 'cdecl', '*._spawnlpe', (('int', None), ('void *', 'obj'), ('int', None), ('int', None)) ),
    '*._spawnv':( 'int', None, 'cdecl', '*._spawnv', (('int', None), ('void *', 'obj'), ('void *', 'ptr')) ),
    '*._spawnve':( 'int', None, 'cdecl', '*._spawnve', (('int', None), ('void *', 'obj'), ('void *', 'ptr'), ('int', None)) ),
    '*._spawnvp':( 'int', None, 'cdecl', '*._spawnvp', (('int', None), ('void *', 'obj'), ('void *', 'ptr')) ),
    '*._spawnvpe':( 'int', None, 'cdecl', '*._spawnvpe', (('int', None), ('void *', 'obj'), ('void *', 'ptr'), ('int', None)) ),
    '*._splitpath':( 'int', None, 'cdecl', '*._splitpath', (('void *', 'ptr'), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._stat':( 'int', None, 'cdecl', '*._stat', (('int', None), ('int', None)) ),
    '*._stat64':( 'int', None, 'cdecl', '*._stat64', (('int', None), ('int', None)) ),
    '*._stati64':( 'int', None, 'cdecl', '*._stati64', (('int', None), ('int', None)) ),
    '*._statusfp':( 'int', None, 'cdecl', '*._statusfp', () ),
    '*._strcmpi':( 'int', None, 'cdecl', '*._strcmpi', (('int', None), ('void *', 'ptr')) ),
    '*._strdate':( 'int', None, 'cdecl', '*._strdate', (('int', None),) ),
    '*._strdup':( 'int', None, 'cdecl', '*._strdup', (('void *', 'ptr'),) ),
    '*._strerror':( 'int', None, 'cdecl', '*._strerror', (('int', None),) ),
    '*._stricmp':( 'int', None, 'cdecl', '*._stricmp', (('int', None), ('void *', 'ptr')) ),
    '*._stricoll':( 'int', None, 'cdecl', '*._stricoll', (('void *', 'ptr'), ('void *', 'ptr')) ),
    '*._strlwr':( 'int', None, 'cdecl', '*._strlwr', (('void *', 'ptr'),) ),
    '*._strncoll':( 'int', None, 'cdecl', '*._strncoll', (('void *', 'ptr'), ('void *', 'ptr'), ('int', None)) ),
    '*._strnicmp':( 'int', None, 'cdecl', '*._strnicmp', (('int', None), ('void *', 'ptr'), ('int', None)) ),
    '*._strnicoll':( 'int', None, 'cdecl', '*._strnicoll', (('void *', 'ptr'), ('void *', 'ptr'), ('int', None)) ),
    '*._strnset':( 'int', None, 'cdecl', '*._strnset', (('int', None), ('int', None), ('int', None)) ),
    '*._strrev':( 'int', None, 'cdecl', '*._strrev', (('int', None),) ),
    '*._strset':( 'int', None, 'cdecl', '*._strset', (('int', None), ('int', None)) ),
    '*._strtime':( 'int', None, 'cdecl', '*._strtime', (('int', None),) ),
    '*._strtoi64':( 'int', None, 'cdecl', '*._strtoi64', (('int', None), ('int', None), ('int', None)) ),
    '*._strtoui64':( 'int', None, 'cdecl', '*._strtoui64', (('int', None), ('int', None), ('int', None)) ),
    '*._strupr':( 'int', None, 'cdecl', '*._strupr', (('void *', 'ptr'),) ),
    '*._swab':( 'int', None, 'cdecl', '*._swab', (('int', None), ('int', None), ('int', None)) ),
    '*._sys_errlist':( 'int', None, 'cdecl', '*._sys_errlist', () ),
    '*._sys_nerr':( 'int', None, 'bfastcall', '*._sys_nerr', (('int', None),) ),
    '*._tell':( 'int', None, 'cdecl', '*._tell', (('int', None),) ),
    '*._telli64':( 'int', None, 'cdecl', '*._telli64', (('int', None),) ),
    '*._tempnam':( 'int', None, 'cdecl', '*._tempnam', (('void *', 'ptr'), ('void *', 'ptr')) ),
    '*._time64':( 'int', None, 'cdecl', '*._time64', (('void *', 'ptr'),) ),
    '*._timezone':( 'int', None, 'bfastcall', '*._timezone', (('int', None),) ),
    '*._tolower':( 'int', None, 'cdecl', '*._tolower', (('int', None),) ),
    '*._toupper':( 'int', None, 'cdecl', '*._toupper', (('int', None),) ),
    '*._tzname':( 'int', None, 'cdecl', '*._tzname', () ),
    '*._tzset':( 'int', None, 'cdecl', '*._tzset', () ),
    '*._ui64toa':( 'int', None, 'msfastcall', '*._ui64toa', (('int', None), ('int', None), ('int', None), ('int', None), ('void *', 'ptr'), ('int', None)) ),
    '*._ui64tow':( 'int', None, 'msfastcall', '*._ui64tow', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._ultoa':( 'int', None, 'cdecl', '*._ultoa', (('int', None), ('void *', 'obj'), ('int', None), ('int', None)) ),
    '*._ultow':( 'int', None, 'cdecl', '*._ultow', (('int', None), ('void *', 'ptr'), ('int', None)) ),
    '*._umask':( 'int', None, 'cdecl', '*._umask', (('int', None),) ),
    '*._ungetch':( 'int', None, 'cdecl', '*._ungetch', (('int', None),) ),
    '*._ungetwch':( 'int', None, 'cdecl', '*._ungetwch', (('int', None),) ),
    '*._unlink':( 'int', None, 'cdecl', '*._unlink', (('int', None),) ),
    '*._unloaddll':( 'int', None, 'cdecl', '*._unloaddll', (('int', None),) ),
    '*._unlock':( 'int', None, 'cdecl', '*._unlock', (('int', None),) ),
    '*._utime':( 'int', None, 'cdecl', '*._utime', (('StringA', None), ('void *', 'ptr')) ),
    '*._utime64':( 'int', None, 'cdecl', '*._utime64', (('StringA', None), ('void *', 'ptr')) ),
    '*._vscprintf':( 'int', None, 'cdecl', '*._vscprintf', (('int', None), ('int', None)) ),
    '*._vscwprintf':( 'int', None, 'cdecl', '*._vscwprintf', (('int', None), ('int', None)) ),
    '*._vsnprintf':( 'int', None, 'cdecl', '*._vsnprintf', (('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._vsnwprintf':( 'int', None, 'cdecl', '*._vsnwprintf', (('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._waccess':( 'int', None, 'cdecl', '*._waccess', (('void *', 'ptr'), ('int', None)) ),
    '*._wasctime':( 'int', None, 'cdecl', '*._wasctime', (('int', None),) ),
    '*._wchdir':( 'int', None, 'cdecl', '*._wchdir', (('int', None),) ),
    '*._wchmod':( 'int', None, 'cdecl', '*._wchmod', (('int', None), ('int', None)) ),
    '*._wcmdln':( 'int', None, 'cdecl', '*._wcmdln', () ),
    '*._wcreat':( 'int', None, 'cdecl', '*._wcreat', (('StringW', None), ('int', None)) ),
    '*._wcsdup':( 'int', None, 'cdecl', '*._wcsdup', (('int', None),) ),
    '*._wcserror':( 'int', None, 'cdecl', '*._wcserror', (('int', None),) ),
    '*._wcsicmp':( 'int', None, 'cdecl', '*._wcsicmp', (('int', None), ('int', None)) ),
    '*._wcsicoll':( 'int', None, 'cdecl', '*._wcsicoll', (('int', None), ('int', None)) ),
    '*._wcslwr':( 'int', None, 'cdecl', '*._wcslwr', (('int', None),) ),
    '*._wcsncoll':( 'int', None, 'cdecl', '*._wcsncoll', (('int', None), ('int', None), ('int', None)) ),
    '*._wcsnicmp':( 'int', None, 'cdecl', '*._wcsnicmp', (('int', None), ('int', None), ('int', None)) ),
    '*._wcsnicoll':( 'int', None, 'cdecl', '*._wcsnicoll', (('int', None), ('int', None), ('int', None)) ),
    '*._wcsnset':( 'int', None, 'cdecl', '*._wcsnset', (('int', None), ('int', None), ('int', None)) ),
    '*._wcsrev':( 'int', None, 'cdecl', '*._wcsrev', (('int', None),) ),
    '*._wcsset':( 'int', None, 'cdecl', '*._wcsset', (('int', None), ('int', None)) ),
    '*._wcstoi64':( 'int', None, 'cdecl', '*._wcstoi64', (('int', None), ('int', None), ('int', None)) ),
    '*._wcstoui64':( 'int', None, 'cdecl', '*._wcstoui64', (('int', None), ('int', None), ('int', None)) ),
    '*._wcsupr':( 'int', None, 'cdecl', '*._wcsupr', (('int', None),) ),
    '*._wctime':( 'int', None, 'cdecl', '*._wctime', (('void *', 'ptr'),) ),
    '*._wctime64':( 'int', None, 'cdecl', '*._wctime64', (('void *', 'ptr'),) ),
    '*._wctype':( 'int', None, 'cdecl', '*._wctype', () ),
    '*._wenviron':( 'int', None, 'cdecl', '*._wenviron', () ),
    '*._wexecl':( 'int', None, 'cdecl', '*._wexecl', () ),
    '*._wexecle':( 'int', None, 'cdecl', '*._wexecle', ( ('int', None), ('int', None)) ),
    '*._wexeclp':( 'int', None, 'cdecl', '*._wexeclp', () ),
    '*._wexeclpe':( 'int', None, 'cdecl', '*._wexeclpe', ( ('int', None), ('int', None)) ),
    '*._wexecv':( 'int', None, 'cdecl', '*._wexecv', ( ('int', None),) ),
    '*._wexecve':( 'int', None, 'cdecl', '*._wexecve', ( ('int', None), ('int', None)) ),
    '*._wexecvp':( 'int', None, 'cdecl', '*._wexecvp', ( ('int', None),) ),
    '*._wexecvpe':( 'int', None, 'cdecl', '*._wexecvpe', ( ('int', None), ('int', None)) ),
    '*._wfdopen':( 'int', None, 'cdecl', '*._wfdopen', (('int', None), ('int', None)) ),
    '*._wfindfirst':( 'int', None, 'cdecl', '*._wfindfirst', (('int', None), ('int', None)) ),
    '*._wfindfirst64':( 'int', None, 'cdecl', '*._wfindfirst64', (('int', None), ('int', None)) ),
    '*._wfindfirsti64':( 'int', None, 'cdecl', '*._wfindfirsti64', (('int', None), ('int', None)) ),
    '*._wfindnext':( 'int', None, 'cdecl', '*._wfindnext', (('int', None), ('int', None)) ),
    '*._wfindnext64':( 'int', None, 'cdecl', '*._wfindnext64', (('int', None), ('int', None)) ),
    '*._wfindnexti64':( 'int', None, 'cdecl', '*._wfindnexti64', (('int', None), ('int', None)) ),
    '*._wfopen':( 'int', None, 'cdecl', '*._wfopen', (('StringW', None), ('int', None)) ),
    '*._wfreopen':( 'int', None, 'cdecl', '*._wfreopen', (('StringW', None), ('int', None), ('int', None)) ),
    '*._wfsopen':( 'int', None, 'cdecl', '*._wfsopen', (('StringW', None), ('int', None), ('int', None)) ),
    '*._wfullpath':( 'int', None, 'cdecl', '*._wfullpath', (('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*._wgetcwd':( 'int', None, 'cdecl', '*._wgetcwd', (('int', None), ('int', None)) ),
    '*._wgetdcwd':( 'int', None, 'cdecl', '*._wgetdcwd', (('int', None), ('int', None), ('int', None)) ),
    '*._wgetenv':( 'int', None, 'cdecl', '*._wgetenv', (('int', None),) ),
    '*._winmajor':( 'int', None, 'cdecl', '*._winmajor', () ),
    '*._winminor':( 'int', None, 'cdecl', '*._winminor', () ),
    '*._winver':( 'int', None, 'cdecl', '*._winver', () ),
    '*._wmakepath':( 'int', None, 'cdecl', '*._wmakepath', (('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._wmkdir':( 'int', None, 'cdecl', '*._wmkdir', (('StringW', None),) ),
    '*._wmktemp':( 'int', None, 'cdecl', '*._wmktemp', (('void *', 'ptr'),) ),
    '*._wopen':( 'int', None, 'cdecl', '*._wopen', (('StringW', None), ('int', None), ('int', None)) ),
    '*._wperror':( 'int', None, 'cdecl', '*._wperror', (('void *', 'ptr'),) ),
    '*._wpgmptr':( 'int', None, 'cdecl', '*._wpgmptr', () ),
    '*._wpopen':( 'int', None, 'cdecl', '*._wpopen', (('void *', 'ptr'), ('int', None)) ),
    '*._wputenv':( 'int', None, 'cdecl', '*._wputenv', (('void *', 'ptr'),) ),
    '*._wremove':( 'int', None, 'cdecl', '*._wremove', (('int', None),) ),
    '*._wrename':( 'int', None, 'cdecl', '*._wrename', (('int', None), ('int', None)) ),
    '*._write':( 'int', None, 'cdecl', '*._write', (('int', None), ('void *', 'ptr'), ('DWORD', None)) ),
    '*._wrmdir':( 'int', None, 'cdecl', '*._wrmdir', (('int', None),) ),
    '*._wsearchenv':( 'int', None, 'cdecl', '*._wsearchenv', (('void *', 'ptr'), ('int', None), ('void *', 'ptr')) ),
    '*._wsetlocale':( 'int', None, 'cdecl', '*._wsetlocale', (('int', None), ('void *', 'ptr')) ),
    '*._wsopen':( 'int', None, 'cdecl', '*._wsopen', (('StringW', None), ('int', None), ('int', None), ('int', None)) ),
    '*._wspawnl':( 'int', None, 'cdecl', '*._wspawnl', (('int', None), ('void *', 'obj')) ),
    '*._wspawnle':( 'int', None, 'cdecl', '*._wspawnle', (('int', None), ('void *', 'obj'), ('int', None), ('int', None)) ),
    '*._wspawnlp':( 'int', None, 'cdecl', '*._wspawnlp', (('int', None), ('void *', 'obj')) ),
    '*._wspawnlpe':( 'int', None, 'cdecl', '*._wspawnlpe', (('int', None), ('void *', 'obj'), ('int', None), ('int', None)) ),
    '*._wspawnv':( 'int', None, 'cdecl', '*._wspawnv', (('int', None), ('void *', 'obj'), ('void *', 'ptr')) ),
    '*._wspawnve':( 'int', None, 'cdecl', '*._wspawnve', (('int', None), ('void *', 'obj'), ('void *', 'ptr'), ('int', None)) ),
    '*._wspawnvp':( 'int', None, 'cdecl', '*._wspawnvp', (('int', None), ('void *', 'obj'), ('void *', 'ptr')) ),
    '*._wspawnvpe':( 'int', None, 'cdecl', '*._wspawnvpe', (('int', None), ('void *', 'obj'), ('void *', 'ptr'), ('int', None)) ),
    '*._wsplitpath':( 'int', None, 'cdecl', '*._wsplitpath', (('void *', 'ptr'), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*._wstat':( 'int', None, 'cdecl', '*._wstat', (('int', None), ('int', None)) ),
    '*._wstat64':( 'int', None, 'cdecl', '*._wstat64', (('int', None), ('int', None)) ),
    '*._wstati64':( 'int', None, 'cdecl', '*._wstati64', (('int', None), ('int', None)) ),
    '*._wstrdate':( 'int', None, 'cdecl', '*._wstrdate', (('int', None),) ),
    '*._wstrtime':( 'int', None, 'cdecl', '*._wstrtime', (('int', None),) ),
    '*._wsystem':( 'int', None, 'cdecl', '*._wsystem', (('int', None),) ),
    '*._wtempnam':( 'int', None, 'cdecl', '*._wtempnam', (('void *', 'ptr'), ('void *', 'ptr')) ),
    '*._wtmpnam':( 'int', None, 'cdecl', '*._wtmpnam', (('int', None),) ),
    '*._wtof':( 'int', None, 'cdecl', '*._wtof', (('void *', 'ptr'),) ),
    '*._wtoi':( 'int', None, 'cdecl', '*._wtoi', (('int', None),) ),
    '*._wtoi64':( 'int', None, 'cdecl', '*._wtoi64', (('int', None),) ),
    '*._wtol':( 'int', None, 'cdecl', '*._wtol', (('int', None),) ),
    '*._wunlink':( 'int', None, 'cdecl', '*._wunlink', (('int', None),) ),
    '*._wutime':( 'int', None, 'cdecl', '*._wutime', (('StringW', None), ('void *', 'ptr')) ),
    '*._wutime64':( 'int', None, 'cdecl', '*._wutime64', (('StringW', None), ('void *', 'ptr')) ),
    '*._y0':( 'int', None, 'cdecl', '*._y0', () ),
    '*._y1':( 'int', None, 'cdecl', '*._y1', () ),
    '*._yn':( 'int', None, 'cdecl', '*._yn', () ),
    '*.abort':( 'int', None, 'stdcall', '*.abort', (('int', None),) ),
    '*.abs':( 'int', None, 'cdecl', '*.abs', (('int', None),) ),
    '*.acos':( 'int', None, 'cdecl', '*.acos', () ),
    '*.asctime':( 'int', None, 'cdecl', '*.asctime', (('int', None),) ),
    '*.asin':( 'int', None, 'cdecl', '*.asin', () ),
    '*.atan':( 'int', None, 'cdecl', '*.atan', () ),
    '*.atan2':( 'int', None, 'cdecl', '*.atan2', (('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*.atexit':( 'int', None, 'cdecl', '*.atexit', (('int', None),) ),
    '*.atof':( 'int', None, 'cdecl', '*.atof', (('void *', 'ptr'),) ),
    '*.atoi':( 'int', None, 'cdecl', '*.atoi', (('int', None),) ),
    '*.atol':( 'int', None, 'cdecl', '*.atol', (('void *', 'ptr'),) ),
    '*.bsearch':( 'int', None, 'cdecl', '*.bsearch', (('int', None), ('int', None), ('int', None), ('int', None), ('void *', 'funcptr')) ),
    '*.calloc':( 'int', None, 'cdecl', '*.calloc', (('int', None), ('int', None)) ),
    '*.ceil':( 'int', None, 'cdecl', '*.ceil', () ),
    '*.clearerr':( 'int', None, 'cdecl', '*.clearerr', (('int', None),) ),
    '*.clock':( 'int', None, 'msfastcall', '*.clock', (('int', None), ('int', None)) ),
    '*.cos':( 'int', None, 'cdecl', '*.cos', () ),
    '*.cosh':( 'int', None, 'cdecl', '*.cosh', (('int', None), ('int', None)) ),
    '*.ctime':( 'int', None, 'cdecl', '*.ctime', (('void *', 'ptr'),) ),
    '*.difftime':( 'int', None, 'cdecl', '*.difftime', (('int', None), ('int', None)) ),
    '*.div':( 'int', None, 'cdecl', '*.div', (('int', None), ('int', None)) ),
    '*.exit':( 'int', None, 'cdecl', '*.exit', (('int', None),) ),
    '*.exp':( 'int', None, 'cdecl', '*.exp', (('int', None), ('int', None)) ),
    '*.fabs':( 'int', None, 'cdecl', '*.fabs', (('int', None), ('int', None)) ),
    '*.fclose':( 'int', None, 'cdecl', '*.fclose', (('int', None),) ),
    '*.feof':( 'int', None, 'cdecl', '*.feof', (('int', None),) ),
    '*.ferror':( 'int', None, 'cdecl', '*.ferror', (('int', None),) ),
    '*.fflush':( 'int', None, 'cdecl', '*.fflush', (('int', None),) ),
    '*.fgetc':( 'int', None, 'cdecl', '*.fgetc', (('int', None),) ),
    '*.fgetpos':( 'int', None, 'cdecl', '*.fgetpos', (('int', None), ('int', None)) ),
    '*.fgets':( 'int', None, 'cdecl', '*.fgets', (('int', None), ('int', None), ('int', None)) ),
    '*.fgetwc':( 'int', None, 'cdecl', '*.fgetwc', (('int', None),) ),
    '*.fgetws':( 'int', None, 'cdecl', '*.fgetws', (('int', None), ('int', None), ('int', None)) ),
    '*.floor':( 'int', None, 'cdecl', '*.floor', () ),
    '*.fmod':( 'int', None, 'cdecl', '*.fmod', (('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*.fopen':( 'int', None, 'cdecl', '*.fopen', (('StringA', None), ('int', None)) ),
    '*.fprintf':( 'int', None, 'cdecl', '*.fprintf', (('void *', 'ptr'), ('int', None)) ),
    '*.fputc':( 'int', None, 'cdecl', '*.fputc', (('int', None), ('void *', 'ptr')) ),
    '*.fputs':( 'int', None, 'cdecl', '*.fputs', (('void *', 'ptr'), ('int', None)) ),
    '*.fputwc':( 'int', None, 'cdecl', '*.fputwc', (('int', None), ('int', None)) ),
    '*.fputws':( 'int', None, 'cdecl', '*.fputws', (('int', None), ('int', None)) ),
    '*.fread':( 'int', None, 'cdecl', '*.fread', (('StringA', None), ('int', None), ('int', None), ('int', None)) ),
    '*.free':( 'int', None, 'cdecl', '*.free', (('void *', 'ptr'),) ),
    '*.freopen':( 'int', None, 'cdecl', '*.freopen', (('StringA', None), ('int', None), ('int', None)) ),
    '*.frexp':( 'int', None, 'cdecl', '*.frexp', () ),
    '*.fscanf':( 'int', None, 'cdecl', '*.fscanf', (('void *', 'ptr'), ('int', None)) ),
    '*.fseek':( 'int', None, 'cdecl', '*.fseek', (('int', None), ('int', None), ('int', None)) ),
    '*.fsetpos':( 'int', None, 'cdecl', '*.fsetpos', (('int', None), ('int', None)) ),
    '*.ftell':( 'int', None, 'cdecl', '*.ftell', (('int', None),) ),
    '*.fwprintf':( 'int', None, 'cdecl', '*.fwprintf', (('void *', 'ptr'), ('int', None)) ),
    '*.fwrite':( 'int', None, 'cdecl', '*.fwrite', (('void *', 'ptr'), ('int', None), ('int', None), ('int', None)) ),
    '*.fwscanf':( 'int', None, 'cdecl', '*.fwscanf', (('void *', 'ptr'), ('int', None)) ),
    '*.getc':( 'int', None, 'cdecl', '*.getc', (('int', None),) ),
    '*.getchar':( 'int', None, 'cdecl', '*.getchar', () ),
    '*.getenv':( 'int', None, 'cdecl', '*.getenv', (('void *', 'ptr'),) ),
    '*.gets':( 'int', None, 'cdecl', '*.gets', (('int', None),) ),
    '*.getwc':( 'int', None, 'cdecl', '*.getwc', (('int', None),) ),
    '*.getwchar':( 'int', None, 'cdecl', '*.getwchar', () ),
    '*.gmtime':( 'int', None, 'cdecl', '*.gmtime', (('void *', 'ptr'),) ),
    '*.is_wctype':( 'int', None, 'cdecl', '*.is_wctype', (('int', None), ('int', None)) ),
    '*.isalnum':( 'int', None, 'cdecl', '*.isalnum', (('int', None),) ),
    '*.isalpha':( 'int', None, 'cdecl', '*.isalpha', (('int', None),) ),
    '*.iscntrl':( 'int', None, 'cdecl', '*.iscntrl', (('int', None),) ),
    '*.isdigit':( 'int', None, 'cdecl', '*.isdigit', (('int', None),) ),
    '*.isgraph':( 'int', None, 'cdecl', '*.isgraph', (('int', None),) ),
    '*.isleadbyte':( 'int', None, 'cdecl', '*.isleadbyte', (('int', None),) ),
    '*.islower':( 'int', None, 'cdecl', '*.islower', (('int', None),) ),
    '*.isprint':( 'int', None, 'cdecl', '*.isprint', (('int', None),) ),
    '*.ispunct':( 'int', None, 'cdecl', '*.ispunct', (('int', None),) ),
    '*.isspace':( 'int', None, 'cdecl', '*.isspace', (('int', None),) ),
    '*.isupper':( 'int', None, 'cdecl', '*.isupper', (('int', None),) ),
    '*.iswalnum':( 'int', None, 'cdecl', '*.iswalnum', (('int', None),) ),
    '*.iswalpha':( 'int', None, 'cdecl', '*.iswalpha', (('int', None),) ),
    '*.iswascii':( 'int', None, 'cdecl', '*.iswascii', (('int', None),) ),
    '*.iswcntrl':( 'int', None, 'cdecl', '*.iswcntrl', (('int', None),) ),
    '*.iswctype':( 'int', None, 'cdecl', '*.iswctype', (('int', None), ('int', None)) ),
    '*.iswdigit':( 'int', None, 'cdecl', '*.iswdigit', (('int', None),) ),
    '*.iswgraph':( 'int', None, 'cdecl', '*.iswgraph', (('int', None),) ),
    '*.iswlower':( 'int', None, 'cdecl', '*.iswlower', (('int', None),) ),
    '*.iswprint':( 'int', None, 'cdecl', '*.iswprint', (('int', None),) ),
    '*.iswpunct':( 'int', None, 'cdecl', '*.iswpunct', (('int', None),) ),
    '*.iswspace':( 'int', None, 'cdecl', '*.iswspace', (('int', None),) ),
    '*.iswupper':( 'int', None, 'cdecl', '*.iswupper', (('int', None),) ),
    '*.iswxdigit':( 'int', None, 'cdecl', '*.iswxdigit', (('int', None),) ),
    '*.isxdigit':( 'int', None, 'cdecl', '*.isxdigit', (('int', None),) ),
    '*.labs':( 'int', None, 'cdecl', '*.labs', (('int', None),) ),
    '*.ldexp':( 'int', None, 'cdecl', '*.ldexp', (('int', None), ('int', None)) ),
    '*.ldiv':( 'int', None, 'cdecl', '*.ldiv', (('int', None), ('int', None)) ),
    '*.localeconv':( 'int', None, 'cdecl', '*.localeconv', () ),
    '*.localtime':( 'int', None, 'cdecl', '*.localtime', (('void *', 'ptr'),) ),
    '*.log':( 'int', None, 'cdecl', '*.log', () ),
    '*.log10':( 'int', None, 'cdecl', '*.log10', () ),
    '*.longjmp':( 'int', None, 'cdecl', '*.longjmp', (('int', None), ('int', None)) ),
    '*.malloc':( 'int', None, 'cdecl', '*.malloc', (('DWORD', None),) ),
    '*.mblen':( 'int', None, 'cdecl', '*.mblen', (('int', None), ('int', None)) ),
    '*.mbstowcs':( 'int', None, 'cdecl', '*.mbstowcs', (('int', None), ('void *', 'ptr'), ('int', None)) ),
    '*.mbtowc':( 'int', None, 'cdecl', '*.mbtowc', (('void *', 'ptr'), ('void *', 'ptr'), ('int', None)) ),
    '*.memchr':( 'int', None, 'cdecl', '*.memchr', (('int', None), ('int', None), ('int', None)) ),
    '*.memcmp':( 'int', None, 'cdecl', '*.memcmp', (('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*.memcpy':( 'int', None, 'cdecl', '*.memcpy', (('void *', 'ptr'), ('void *', 'ptr'), ('int', None)) ),
    '*.memmove':( 'int', None, 'cdecl', '*.memmove', (('int', None), ('void *', 'ptr'), ('int', None)) ),
    '*.memset':( 'int', None, 'cdecl', '*.memset', (('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*.mktime':( 'int', None, 'cdecl', '*.mktime', (('int', None),) ),
    '*.modf':( 'int', None, 'cdecl', '*.modf', (('int', None), ('int', None)) ),
    '*.perror':( 'int', None, 'cdecl', '*.perror', (('void *', 'ptr'),) ),
    '*.pow':( 'int', None, 'cdecl', '*.pow', () ),
    '*.printf':( 'int', None, 'cdecl', '*.printf', (('int', None),) ),
    '*.putc':( 'int', None, 'cdecl', '*.putc', (('int', None), ('void *', 'ptr')) ),
    '*.putchar':( 'int', None, 'cdecl', '*.putchar', (('int', None),) ),
    '*.puts':( 'int', None, 'cdecl', '*.puts', (('void *', 'ptr'),) ),
    '*.putwc':( 'int', None, 'cdecl', '*.putwc', (('int', None), ('int', None)) ),
    '*.putwchar':( 'int', None, 'cdecl', '*.putwchar', (('int', None),) ),
    '*.qsort':( 'int', None, 'stdcall', '*.qsort', ( ('int', None), ('int', None), ('void *', 'funcptr'), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*.raise':( 'int', None, 'cdecl', '*.raise', (('int', None),) ),
    '*.rand':( 'int', None, 'cdecl', '*.rand', () ),
    '*.realloc':( 'int', None, 'cdecl', '*.realloc', (('void *', 'ptr'), ('DWORD', None)) ),
    '*.remove':( 'int', None, 'cdecl', '*.remove', (('int', None),) ),
    '*.rename':( 'int', None, 'cdecl', '*.rename', (('int', None), ('int', None)) ),
    '*.rewind':( 'int', None, 'cdecl', '*.rewind', (('int', None),) ),
    '*.scanf':( 'int', None, 'cdecl', '*.scanf', (('int', None),) ),
    '*.setbuf':( 'int', None, 'cdecl', '*.setbuf', (('int', None), ('int', None)) ),
    '*.setlocale':( 'int', None, 'cdecl', '*.setlocale', (('int', None), ('void *', 'obj')) ),
    '*.setvbuf':( 'int', None, 'cdecl', '*.setvbuf', (('int', None), ('int', None), ('int', None), ('DWORD', None)) ),
    '*.signal':( 'int', None, 'cdecl', '*.signal', (('int', None), ('int', None)) ),
    '*.sin':( 'int', None, 'cdecl', '*.sin', () ),
    '*.sinh':( 'int', None, 'cdecl', '*.sinh', (('int', None), ('int', None)) ),
    '*.sprintf':( 'int', None, 'cdecl', '*.sprintf', (('int', None), ('int', None)) ),
    '*.sqrt':( 'int', None, 'cdecl', '*.sqrt', () ),
    '*.srand':( 'int', None, 'cdecl', '*.srand', (('int', None),) ),
    '*.sscanf':( 'int', None, 'cdecl', '*.sscanf', (('void *', 'ptr'), ('int', None)) ),
    '*.strcat':( 'int', None, 'cdecl', '*.strcat', (('void *', 'ptr'), ('void *', 'ptr')) ),
    '*.strchr':( 'int', None, 'cdecl', '*.strchr', (('int', None), ('int', None)) ),
    '*.strcmp':( 'int', None, 'cdecl', '*.strcmp', (('void *', 'ptr'), ('int', None)) ),
    '*.strcoll':( 'int', None, 'cdecl', '*.strcoll', (('void *', 'ptr'), ('void *', 'ptr')) ),
    '*.strcpy':( 'int', None, 'cdecl', '*.strcpy', (('void *', 'ptr'), ('void *', 'ptr')) ),
    '*.strcspn':( 'int', None, 'cdecl', '*.strcspn', (('int', None), ('int', None)) ),
    '*.strerror':( 'int', None, 'cdecl', '*.strerror', (('int', None),) ),
    '*.strftime':( 'int', None, 'cdecl', '*.strftime', (('void *', 'ptr'), ('int', None), ('void *', 'ptr'), ('int', None)) ),
    '*.strlen':( 'int', None, 'cdecl', '*.strlen', (('void *', 'ptr'),) ),
    '*.strncat':( 'int', None, 'cdecl', '*.strncat', (('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*.strncmp':( 'int', None, 'cdecl', '*.strncmp', (('int', None), ('int', None), ('int', None)) ),
    '*.strncpy':( 'int', None, 'cdecl', '*.strncpy', (('void *', 'ptr'), ('void *', 'ptr'), ('int', None)) ),
    '*.strpbrk':( 'int', None, 'cdecl', '*.strpbrk', (('int', None), ('int', None)) ),
    '*.strrchr':( 'int', None, 'cdecl', '*.strrchr', (('int', None), ('int', None)) ),
    '*.strspn':( 'int', None, 'cdecl', '*.strspn', (('int', None), ('int', None)) ),
    '*.strstr':( 'int', None, 'cdecl', '*.strstr', (('int', None), ('void *', 'ptr')) ),
    '*.strtod':( 'int', None, 'cdecl', '*.strtod', (('void *', 'ptr'), ('int', None)) ),
    '*.strtok':( 'int', None, 'cdecl', '*.strtok', (('int', None), ('int', None)) ),
    '*.strtol':( 'int', None, 'cdecl', '*.strtol', (('int', None), ('int', None), ('int', None)) ),
    '*.strtoul':( 'int', None, 'cdecl', '*.strtoul', (('int', None), ('int', None), ('int', None)) ),
    '*.strxfrm':( 'int', None, 'cdecl', '*.strxfrm', (('void *', 'ptr'), ('void *', 'ptr'), ('int', None)) ),
    '*.swprintf':( 'int', None, 'cdecl', '*.swprintf', (('int', None), ('int', None)) ),
    '*.swscanf':( 'int', None, 'cdecl', '*.swscanf', (('int', None), ('int', None)) ),
    '*.system':( 'int', None, 'cdecl', '*.system', (('int', None),) ),
    '*.tan':( 'int', None, 'cdecl', '*.tan', () ),
    '*.tanh':( 'int', None, 'cdecl', '*.tanh', (('int', None), ('int', None)) ),
    '*.time':( 'int', None, 'cdecl', '*.time', (('void *', 'ptr'),) ),
    '*.tmpfile':( 'int', None, 'cdecl', '*.tmpfile', () ),
    '*.tmpnam':( 'int', None, 'cdecl', '*.tmpnam', (('void *', 'ptr'),) ),
    '*.tolower':( 'int', None, 'cdecl', '*.tolower', (('int', None),) ),
    '*.toupper':( 'int', None, 'cdecl', '*.toupper', (('int', None),) ),
    '*.towlower':( 'int', None, 'cdecl', '*.towlower', (('int', None),) ),
    '*.towupper':( 'int', None, 'cdecl', '*.towupper', (('int', None),) ),
    '*.ungetc':( 'int', None, 'cdecl', '*.ungetc', (('int', None), ('int', None)) ),
    '*.ungetwc':( 'int', None, 'cdecl', '*.ungetwc', (('int', None), ('int', None)) ),
    '*.vfprintf':( 'int', None, 'cdecl', '*.vfprintf', (('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*.vfwprintf':( 'int', None, 'cdecl', '*.vfwprintf', (('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*.vprintf':( 'int', None, 'cdecl', '*.vprintf', (('int', None), ('int', None)) ),
    '*.vsprintf':( 'int', None, 'cdecl', '*.vsprintf', (('int', None), ('int', None), ('int', None)) ),
    '*.vswprintf':( 'int', None, 'cdecl', '*.vswprintf', (('int', None), ('int', None), ('int', None)) ),
    '*.vwprintf':( 'int', None, 'cdecl', '*.vwprintf', (('int', None), ('int', None)) ),
    '*.wcscat':( 'int', None, 'cdecl', '*.wcscat', (('int', None), ('int', None)) ),
    '*.wcschr':( 'int', None, 'cdecl', '*.wcschr', (('int', None), ('int', None)) ),
    '*.wcscmp':( 'int', None, 'cdecl', '*.wcscmp', (('int', None), ('int', None)) ),
    '*.wcscoll':( 'int', None, 'cdecl', '*.wcscoll', (('int', None), ('int', None)) ),
    '*.wcscpy':( 'int', None, 'cdecl', '*.wcscpy', (('int', None), ('void *', 'ptr')) ),
    '*.wcscspn':( 'int', None, 'cdecl', '*.wcscspn', (('int', None), ('int', None)) ),
    '*.wcsftime':( 'int', None, 'cdecl', '*.wcsftime', (('int', None), ('int', None), ('int', None), ('int', None)) ),
    '*.wcslen':( 'int', None, 'cdecl', '*.wcslen', (('void *', 'ptr'),) ),
    '*.wcsncat':( 'int', None, 'cdecl', '*.wcsncat', (('int', None), ('int', None), ('int', None)) ),
    '*.wcsncmp':( 'int', None, 'cdecl', '*.wcsncmp', (('int', None), ('int', None), ('int', None)) ),
    '*.wcsncpy':( 'int', None, 'cdecl', '*.wcsncpy', (('int', None), ('int', None), ('int', None)) ),
    '*.wcspbrk':( 'int', None, 'cdecl', '*.wcspbrk', (('int', None), ('int', None)) ),
    '*.wcsrchr':( 'int', None, 'cdecl', '*.wcsrchr', (('int', None), ('int', None)) ),
    '*.wcsspn':( 'int', None, 'cdecl', '*.wcsspn', (('int', None), ('int', None)) ),
    '*.wcsstr':( 'int', None, 'cdecl', '*.wcsstr', (('int', None), ('int', None)) ),
    '*.wcstod':( 'int', None, 'cdecl', '*.wcstod', (('void *', 'ptr'), ('int', None)) ),
    '*.wcstok':( 'int', None, 'cdecl', '*.wcstok', (('int', None), ('int', None)) ),
    '*.wcstol':( 'int', None, 'cdecl', '*.wcstol', (('int', None), ('int', None), ('int', None)) ),
    '*.wcstombs':( 'int', None, 'cdecl', '*.wcstombs', (('void *', 'ptr'), ('void *', 'ptr'), ('int', None)) ),
    '*.wcstoul':( 'int', None, 'cdecl', '*.wcstoul', (('int', None), ('int', None), ('int', None)) ),
    '*.wcsxfrm':( 'int', None, 'cdecl', '*.wcsxfrm', (('void *', 'ptr'), ('int', None), ('int', None)) ),
    '*.wctomb':( 'int', None, 'cdecl', '*.wctomb', (('void *', 'ptr'), ('int', None)) ),
    '*.wprintf':( 'int', None, 'cdecl', '*.wprintf', (('int', None),) ),
    '*.wscanf':( 'int', None, 'cdecl', '*.wscanf', (('int', None),) ),

} # END
